- src/components/Input/index.js
Hover on input brings the wrong type of cursor. Removing the class "pointer" fixes it.
> Remove pointer class from input

- CHANGELOG.md
- src/components/Dropdown/README.md
- src/components/Dropdown/index.js
Use native dropdown instead of the custom one. 
Also changes the prop `optionsCaption` to `placeholder`.
Please test on a range of different devices and browsers.
> Native dropdown

- CHANGELOG.md
- package.json
- src/components/icon/Download/index.js
- src/components/icon/Upload/index.js
> Update weight of icons

- CHANGELOG.md
- react/components/Radio/index.js
Title is self explanatory.
Use case:
> Allows node as radio labels

- CHANGELOG.md
- manifest.json
- package.json
- react/Checkbox.js
- react/components/Spinner/index.js
Export Checkbox component as an render app
Change `search-result` to import styleguide components only through Render. 
[PR search-result](https://github.com/vtex-apps/search-result/pull/5)
https://claudivan--storecomponents.myvtexdev.com/smartphones
> Export Checkbox component as an render app

- CHANGELOG.md
- manifest.json
- package.json
- react/EmptyState.js
- react/IconArrowBack.js
- react/IconArrowDown.js
- react/IconArrowUp.js
- react/IconCaretDown.js
- react/IconCaretLeft.js
- react/IconCaretRight.js
- react/IconCaretUp.js
- react/IconClock.js
- react/IconCog.js
- react/IconCopy.js
- react/IconDelete.js
- react/IconExternalLink.js
- react/IconExternalLinkMini.js
- react/IconFilter.js
- react/IconHelp.js
- react/IconLink.js
- react/IconSave.js
- react/RadioGroup.js
- react/Tabs.js
- react/components/Radio/index.js
- react/components/RadioGroup/README.md
- react/components/RadioGroup/index.js
Adds RadioGroup component. API is intentionally about the same as the `Dropdown` component, in order for both to be easily interchangeable.
> RadioGroup

- react/components/Button/README.md
- react/components/Button/index.js
Podemos adicionar o danger button ao styleguide?
Detalhe, só tem duas versões de vermelho no vtex-tachyons: `washed-red` e `red`. O `washed-red` é muito claro pra funciona no botão, por isso usei o `red`. Também não adicionei nenhuma cor de _hover_ pois não tinha disponível um vermelho diferente.
> Add red danger buttons

- CHANGELOG.md
- react/components/Textarea/README.md
- react/components/Textarea/index.js
Fix issue where only the default value would change with input from Textarea. This also allows the use of controlled value in React.
> Add controlled value to Textarea

- CHANGELOG.md
- react/components/Badge/README.md
- react/components/Badge/index.js
We decided to keep the "custom colors" option for the badges, but we added 3 types: success, warning and error. We also updated the examples:
.
> Update badge to receive semantic colors

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Dropdown/index.js
- react/components/Input/index.js
Refs created with the new `React.createRef()`, introduced in React 16.3 are of type `object`, instead of `function`. This PR adds support for both commonly used types, as explained [here](https://reactjs.org/docs/refs-and-the-dom.html).
> Fix forwardedRef Proptype

- CHANGELOG.md
- react/components/Textarea/README.md
- react/components/Textarea/index.js
Add character countdown to Textarea whenever `maxLength` is defined. Text can be customized using the `characterCountdownText` prop.
Behaviour: becomes red near the limit (last 10 characters)
> Add optional countdown to Textarea

- react/components/Badge/README.md
These low contrast examples were mentioned in the documentation of the component but were removed in a previous commit.
> Rollback low prominence examples that were removed

- CHANGELOG.md
- manifest.json
- package-lock.json
- package.json
- react/components/Table/index.js
There was a client reporting that whenever his locale changed the table wouldn't update unless he forced re-rendering somehow (e.g. changing some row content, adding/deleting row)
That does make sense, because Table is a PureComponent, and since locale is in the context, not in props and not in the state, it really was designed not to update itself automatically in this case.
So we should provide a way the user can tell the table to re-render whenever he wants. Passing through this additional prop will do this, so the client can create a hash based on whatever he wants to tell the table when to update. 
In this case I could instruct him to use the locale as a key and it would re-render as expected when the locale changed.
I tried to explain the problem so maybe we can discuss a different …
> forces table re-render when key changes

- CHANGELOG.md
- react/components/Input/README.md
- react/components/Input/index.js
- Closes https://github.com/vtex/styleguide/issues/245
- Updates color token to match Figma's design
- Fixes unnecessary `<span>` in example that were leading the icon to be out of center.
Before
===
After
===
> Improve suffixIcon documentation and fix color token

- .gitignore
- CHANGELOG.md
- README.md
- _releasy.json
- manifest.json
- package.json
- react/IconOptionsDots.js
- react/IconVisibilityOff.js
- react/IconVisibilityOn.js
- react/PasswordInput.js
- react/Slider.js
- react/components/icon/OptionsDots/index.js
- react/components/icon/README.md
Allow CSS files in styleguide
Style files are not allowed, they are ignored during transpilation
Create a style for a component, use compile script and then use npm link to use styleguide locally and test if the style is being applied.
> Update babel script to copy files ignoring *.md

- CHANGELOG.md
- react/components/PageHeader/index.js
Add flex-wrap to PageHeader so it can fit on small screens
Before:
After:
> Add flex-wrap to PageHeader to fit on small screens

- .eslintrc
- package.json
- react/components/MultiSelect/index.js
- react/components/Table/index.js
- react/components/Toast/README.md
- yarn.lock
Changes the importing method of lodash functions, to avoid including the entire lodash lib, reducing the file size
Before
After
(both are the unminified, ungzipped, dev build of the styleguide from vtex io)
> Prevent importing of the entire lodash lib

- CHANGELOG.md
We launched a breaking change in version v8.0.0 and v8.1.0. If someone was trying to figure out what was the breaking changes of the major version 8.x it would only read the v8.0.0 changelog. This commits removes v8.0.0 release and compiles the releases of v8.0.0, v8.0.1 and v8.1.0 in a single release, so this wouldnt be confusing.
Next time we will not do that and will launch a new major instead, avoiding this type of hack.
> Fix changelog to compile breaking changes in a single release

- CHANGELOG.md
- react/components/Table/README.md
- react/components/Table/SimpleTable.js
- adds title in headerRenderer params.
- Fixes vtex/styleguide/issues/442
> Hotfix - add title as param in headerRenderer callback

- CHANGELOG.md
- docs/styles/breakpoints.md
`Syntax` field for the `Not Small` breakpoint should be `-ns`, not `-nl`
> Fix typo on `breakpoints.md`

- CHANGELOG.md
- react/components/Input/README.md
- react/components/Input/index.js
- Removes hover effects of `read-only` Input, since it's not actually interactive.
- Fixes type color on disabled state.
> Fix styles for disabled and read-only states

- react/components/ActionMenu/Menu.js
- react/components/ActionMenu/README.md
- react/components/ActionMenu/index.js
I was checking the current state of the ActionMenu development and implemented some suggested changes.
- Removes the "container" from the Menu, which was trying to be opinionated about the button alignment in the layout. I think it doesn't make sense, the button alignment should be handled by its parent.
- The caret icon is now opt-out instead of opt-in. Renamed prop to `hideCaretIcon`, with default value equal to `false`.
- Remove `shouldCloseOnClick` prop, making it the default behavior.
- Rename prop `boxWidth` to `menuWidth`, to avoid confusing with our Box component. Also made it default to `100%`.
- Fix vertical alignment of caret icon.
- Improves documentation & examples to present more possible options and avoid undesiderable usage.
> ActionMenu improvements

- CHANGELOG.md
- react/components/InputPassword/index.js
:bezerra:
Sets its font to monospaced to prevent the text width from shifting. Also removes spellcheck from it
After:
Before:
> Adjust InputPassword styling

- styleguide.config.js
- Reorder components and groups to be ordered alphabetically
- Finally, makes every component fill only one page, no more pages for groups of components.
> Refactor components' organization and show 1 per page

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Toast/Toast.js
- Fix the `Toast` line breaking for small messages with a long action text.
Just run styleguide on the branch `fix/toast-linebreak`. You should create an VTEX IO app that is mobile friendly and invoke the toast with different text lengths and actions.
> fixes toast line breaking for big buttons on mobile

- CHANGELOG.md
- manifest.json
- package.json
- react/components/PageBlock/README.md
- react/components/PageBlock/index.js
Allow users to set side content on the `PageBlock` header like the `PageHeader`.
Working example: https://kevin--cea.myvtex.com/admin/insights
> Add aside prop to pageBlock

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
Problem:
With this fix:
If the block prop is true, make the label have the width of parent view. Already has a ph to not touch the border
> Make button label fill view if block

- react/components/Select/README.md
- react/components/Select/index.js
It adds a flag prop that renders a different component, which is the CreatableSelect, where you can add custom options.
There is a problem with the limit of things you can select, this is what happens:
After debugging a little bit, I found out that if I remove this function getValueContainerHeightFromSize() from the styles prop it works better:
But I didn't remove the function, because I don't know if this is working good for any other use case.
> Add creatable option

- CHANGELOG.md
- manifest.json
- package.json
- react/components/InputCurrency/index.js
The **InputCurrency** `onChange`callback was using the formatted value. This PR changes the callback to use the float value.
> Fix onChange callback to use the float value and not the formatted value

- react/components/InputCurrency/README.md
- react/components/InputCurrency/index.js
- Manually added some prop docs while https://github.com/vtex/styleguide/issues/515 isn't fixed.
- Makes `currencyCode` required.
- Remove required statement from `BaseInput` props (they're actually mutually exclusive).
> Currency Input improvements

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/README.md
- react/components/Table/SimpleTable.js
When using a table with fullWidth on, the schema property **width** is not respected.
This adds a new schema property named **minWidth** that controls the minimum desired width for a column. 
Now, the **width** property will always be respected. If there is no available space remaining (after the **width** subtraction) for the column it will respect its **minWidth** and create a horizontal scrolling.
As you can see in the image above, the columns Name and Email have the **width** property but it's not being respected in the UI (260px).
> Add minWidth prop to column schema

- CHANGELOG.md
- react/components/Layout/README.md
- react/components/Layout/index.js
As discussed in the Styleguide meeting the 17th January.
> Make PageLayout occupy all available horizontal space

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Checkbox/README.md
- react/components/Checkbox/index.js
Proposal: remove the bottom margin of the `Checkbox` element. It should be the responsibility of the app importing it. It also allows to use the element "naked" (ex: within the table to select all rows).
> Remove bottom margin

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Checkbox/index.js
Make label not required to use the checkbox on its own. 
Ex: as a column checker in the Table.
> Remove isRequired attribute

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/Toolbar.js
Allow table's toolbar buttons to use the `isLoading` state:
> [TABLE] Add isLoading prop

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
- react/components/ButtonWithIcon/index.js
- react/components/Dropdown/index.js
- react/components/Input/index.js
- react/components/InputCurrency/index.js
- react/components/InputPassword/index.js
- react/components/InputSearch/index.js
- react/modules/withForwardedRef.js
This PR intends to fix ref forwarding for Button/ButtonWithIcon. We also standardized other input components that needed to forward refs.
As an extra, this fixed (it seems) the documentation for some components:
- Before:
- After
> Input components using HOC withForwardRef

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Select/index.js
Before this PR, we were applying focus to the input component of the **EXPERIMENTAL_Select** in the `componentDidUpdate` lifecycle. This was causing some weird focus behavior when a change in another part of the page triggers an update on the **EXPERIMENTAL_Select** and, therefore, the select was focused, even though the user was not using the component.
Now, we only focus the **EXPERIMENTAL_Select** component when is being used.
> Fix focus behavior when typing in the search input

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Tag/README.md
- react/components/Tag/index.js
Add a new prop to tags. Now a tag can have a low prominence version, with borders and no background color.
Our low prominence tags examples on styleguide weren't actually a prop, and the visual suggested wasn't attending minimum contrast standards.
> Add Low prominence variation to tags

- CHANGELOG.md
- manifest.json
- package.json
- react/components/ColorPicker/HexInput.js
- react/components/ColorPicker/index.js
Issues:
1. `colorHistory` prop is not defined but component breaks without it.
- **How to Reproduce**: Just create a ColorPicker component without defining the `colorHistory` prop and try to edit a color.
- **Fix**: Add the prop to PropTypes.
2. Hex value only updates after a click.
- **How to Reproduce**: Go to the [ColorPicker documentation page](https://styleguide.vtex.com/#/Components/Forms/ColorPicker) and scroll to the component without clicking. Values on Hex Input all show `#000000` instead of the correct value.
- **Fix**: Update state on `componentDidMount` instead of only on `componentDidUpdate`
> Fix problems on ColorPicker

- react/IconMinus.js
- react/components/icon/Minus/index.js
- react/components/icon/README.md
I'm adding the `minus` icon to the Styleguide. We are going to need it at this screen:
> Add Minus Icon to styleguide

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Tabs/README.md
- react/components/Tabs/Tab.js
Add disable state to tabs, styling them in grayscale and preventing the click event to be triggered.
> Add disabled state to tabs

- .gitignore
- CHANGELOG.md
- package.json
Users of this library as a npm module are having issues to use it, since scripts inside the directory `modules` are not being published to npm.
See:
https://unpkg.com/@vtex/styleguide@8.18.3/
You can't find the module `withForwardedRef.js` there.
> Fix npm build

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/README.md
- react/components/Table/SimpleTable.js
- react/components/Table/index.js
Add a column used for actions to be executed on each line. This is controled by a prop called `lineActions`:
```js
lineActions: PropTypes.arrayOf(
PropTypes.shape({
label: PropTypes.func,
isDangerous: PropTypes.bool,
onClick: PropTypes.func,
})
),
```
1. Run `yarn start`
2. Navigate to http://localhost:6060/#/Components/Display/Table
3. The 2nd example is for this feature
> Table line actions

- CHANGELOG.md
- react/modules/withForwardedRef.js
1. oneOf requires an array
2. `Element` is not available in the global namespace while running jest, so we get it from `window` instead
> Fix withForwardedRef

- CHANGELOG.md
- manifest.json
- package.json
- react/components/InputCurrency/index.js
InputCurrency uses NumberFormat underneath, and I discovered a problem with `ref` prop in NumberFormat. 
For more info: 
Issue on github: https://github.com/s-yadav/react-number-format/issues/125
NumberFormat doc: https://github.com/s-yadav/react-number-format#getting-reference
> Fix ref prop on InputCurrency

- CHANGELOG.md
- manifest.json
- package.json
- react/components/PageHeader/index.js
When without 'children', 'subtitle' was being misplaced on the component. And when without 'subtitle', 'children' was getting too far away from the 'title'.
> Fix behavior of subtitle prop

- CHANGELOG.md
- manifest.json
- package.json
- react/ToastContext.js
- react/components/ToastProvider/README.md
- react/components/ToastProvider/ToastManager.js
- react/components/ToastProvider/index.js
**There is no breaking changes. ToastProvider API is the same.**
As the title says, with the `ToastContext` exported, we can now use it with Hooks (for those who don't want to use the `withToast` HOC in functional components):
```jsx
import { useContext } from 'react'
import { ToastContext } from 'vtex.styleguide'
function Component() {
...
const { showToast, hideToast, toastState } = useContext(ToastContext)
...
}
```
[Access the workspace](http://toast--storecomponents.myvtex.com) and open the dev tools and click the `Network > Offline` option (or turn off your device's network). Then click the buy button to see the offline toast be replaced but when the buy button toast goes away, the offline toast goes up again.
> Export ToastContext to allow useContext and ToastManager is now a HOC

- react/components/InputCurrency/README.md
Removes hardcoded prop docs that are not necessary anymore since https://github.com/vtex/styleguide/issues/515 got fixed.
> Remove hardcoded InputCurrency props docs

- CHANGELOG.md
- manifest.json
- package.json
- react/modules/withForwardedRef.js
The `Proptypes.instaceof(null)` was causing the error:
[Workspace with these changes](https://searchproptypes--storecomponents.myvtex.com/)
> Fixed error caused by intanceof null on withFowardedRef module

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Pagination/index.js
- react/components/Table/sampleData.js
Fixes pagination when the total amount of items in not a multiple of the rows length.
Closes https://github.com/vtex/styleguide/issues/554
Before:
After:
> Fix table pagination

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Toggle/index.js
Checkbox input "outside" HMTL in terms of positioning.
["The absolutely positioned element will position itself relative to the nearest positioned ancestor."](https://medium.freecodecamp.org/how-to-understand-css-position-absolute-once-and-for-all-b71ca10cd3fd)
> Set checkbox input parent's position to relative

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/Toolbar.js
This PR fixes the case where you want to use the `Toolbar` without the search bar.
Before: 
After:
> Table's toolbar without the search bar is aligned to the left

- CHANGELOG.md
- manifest.json
- package.json
- react/ProgressBar.js
- react/components/ProgressBar/README.md
- react/components/ProgressBar/Step.js
- react/components/ProgressBar/index.js
- react/components/ProgressBar/styles.css
- styleguide.config.js
Add a `ProgressBar` component to the Styleguide. This component should be used to represent the progression of some workflow by representing which steps are completed, in progress or yet to do.
Example with the 3 types of steps, in order: _completed, in progress, to do_:
The inStore team needs this component for displaying in which step the picking activity is for the vendor in charge of the picking.
> Add ProgressBar component to the Styleguide

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Toggle/index.js
I needed this prop because I'm using `formik` and the way it changes of current state is getting the name of the target (or the id) to change the values of the form. I could use id too (and I will until this PR is merged), but since the rest of the code is using name and usually when you use formik you pass the `name` prop to the element, doesn't make sense to let only the `Toggle` component passing the id.
Another point is that `Input` passed the prop name to it's `input` element, so I thought that `Toggle` should be passing too.
> Add name prop to toggle component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Collapsible/index.js
when first rendered with `isOpen` set to `true`, the component was still closed.
> Fix collapsible not open on first render

- CHANGELOG.md
- manifest.json
- package.json
- react/CheckboxGroup.js
- react/components/Checkbox/README.md
- react/components/CheckboxGroup/README.md
- react/components/CheckboxGroup/index.js
- react/components/Toggle/README.md
- styleguide.config.js
Add the `CheckboxGroup` component which creates a group of `Checkbox` components based on its props. 
The group of checkbox should be somehow related, the main checkbox is also created allowing the checking or unchecking of all inner checkboxes.
The spacing between the checkbox is optimized for mobile applications. This can be later modified by props in a future PR.
Also, some references to other components were modified as they seemed to not be working properly.
> Add CheckboxGroup component to the Styleguide and fix some page links

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Collapsible/README.md
- react/components/Collapsible/index.js
Add a new prop to the `Collapsible` component named `caretColor`. This props will apply a CSS class to the Caret Icon depending on the value chosen. The possible values are `black`,  `primary` and `muted`.
The `muted` prop now is marked as deprecated, use the muted option of the `caretColor` instead.
> Add caretColor prop to the Collapsible component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/FilterOptions/FilterColapsible.js
- react/components/FilterOptions/index.js
If there are more than 3 filter options, the `Collapsible`s start opened by default.
For modal use, if the `Collapsible`s starting opened helps spread the content over the container.
> Change FilterOptions to begin with opened collapsibles when it have few options

- assets/analytics.js
- styleguide.config.js
Now Google Analytics tracking is done from inside Tag Manager, which enables us to track changes in the URL and forcing Page View events. This is necessary since the Styleguidist routing system uses fragments (those parts after the `#`), which GA doesn't support by default.
> Replaces GA with Google Tag Manager

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/README.md
- react/components/Table/SimpleTable.js
Add property to align right the text of a header cell.
Useful when a column is a sortable of monetary values which was not possible before.
`yarn styleguide` in this branch.
> Add headerRight property

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
- react/components/EXPERIMENTAL_Select/index.js
- react/components/Spinner/README.md
- react/components/Spinner/index.js
- react/components/Textarea/index.js
1. Fix `Button`'s disabled border.
2. Set message shown to user on `Select` when the `creatable` prop is `true`.
3. Control `resize` behavior of `Textarea`.
4. Get commits from [https://github.com/vtex/styleguide/pull/536/](https://github.com/vtex/styleguide/pull/536/) that weren't merged.
Old disabled Button:
New disabled Button:
You can now translate the message shown when creating an option using `Select`:
Old resize behavior allows the user to break the UI:
Allows `vertical` resize only in `Textarea`:
`Spinner` using CSS animations doesn't stop spinning when main thread is busy processing stuff :P
> Misc improvements

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Alert/README.md
- react/components/Alert/index.js
Fix Alert's content children position to top.
Center alignment.
> Fix Alert's content position

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/SimpleTable.js
- react/components/Table/index.js
- Density is now considered as a rerender param. So when line density is toggled, the table should recalculate i'ts height and rerender the lines.
- Necessity to manually controll render when line density changes.
> Considers line density as param for rerender

- CHANGELOG.md
- manifest.json
- package.json
- react/components/PageHeader/index.js
To fix pageHeader emitting a warning when the prop title is a formattedMessage node.
Error warnings that shouldn't be there.
> Fix pageheader not accepting formattedmessage

- CHANGELOG.md
- manifest.json
- package.json
- react/components/NumericStepper/index.js
Muda NumericStepper modo lean para usar input em vez de div
Adiciona hover para modo lean do numeric stepper
O numericStepper tem uma prop 'lean' que está descrita como "Lean mode, with subtler styling" mas ela também muda o container do número, no estilo normal ele é um Input e no lean ele se torna uma div.
Isso tira a funcionalidade de poder escrever a quantidade diretamente além de acabar sendo uma mudança brusca para algo que deveria ser só de style (input -> div).
Running locally
> Change NumericStepper lean mode to use input

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Modal/index.js
- Add padding-top to **Modal** iff without `title` prop
Modal without title prop on admin with weird spaces
Running locally
Before:
After:
> Add padding-top to titleless Modal

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Modal/index.js
- react/components/ModalDialog/index.js
as the title says. 
The prop `onExited` already exists in `ResponsiveModal` (react component internally used). Just passed the prop to parent component ( `ModalDialog`) as  `onCloseTransitionFinish`.
What `onCloseTransitionFinish` does? The function you pass to this prop will be fired when the Modal has exited and the animation is finished.
1. [Workspace](https://mariana--storecomponents.myvtex.com/admin/collections).
> Add onExited prop

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Radio/index.js
Add break-word css prop to Radio label.
Fixes https://github.com/vtex/styleguide/issues/552
Checkout and resize browser window.
Before:
After:
> Add break-word on label

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/Toolbar.js
- react/components/Table/index.js
Add disabled state for toolbar upload & download options.
Download button has to be disabled in my app when there is nothing to be downloaded.
Checkout and add `disabled: true` locally.
Enabled:
Disabled:
Both:
> Add disabled state for toolbar options

- CHANGELOG.md
- manifest.json
- package.json
- react/components/FloatingActionBar/README.md
- react/components/FloatingActionBar/index.js
`FloatingActionBar` should have better props shape so it can be more customizable.
There was no possible way to add different props to the `Save` and `Cancel` buttons. For example, before this PR, you cannot set a `loading` state to them.
> FloatingActionBar now has better props shape

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Collapsible/index.js
[Click here to access the workspace.](https://waza--storecomponents.myvtex.com/admin/collections/374)
> Collapse button is not correctly aligned when the header title is longer than the width

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
Fix styleguide button tertiary when collapse property is passed
By checking the visual of collapsed tertiary button
> Fix collapse of tertiary button

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Box/index.tsx
Apply spacing to `Box` in small screen sizes too.
Before:
After:
> Apply same spacing to Box in all screen sizes

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
- react/components/ButtonGroup/index.js
- react/components/ColorPicker/ColorHistory.js
- react/components/utils/index.js
- react/docs/Pathline.js
- react/modules/deprecated.js
Fix warning message: `Failed prop type: Right-hand side of 'instanceof' is not callable`
Checkout branch, run styleguide locally and open the `Components/Forms/ButtonGroup` url. No message should appear. Add a component not in the list of authorized components and watch the warning in console.
When adding a `Card` to the list:
> Update proptypes verification

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
Remove `iconOnly` from ternary that sets `Button`'s type.
`ActionMenu`'s `ButtonWithIcon` with just an icon inside a `<form>` was always submitting the form.
> Fix: Button is always submit when has iconOnly

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/CheckboxContainer.js
Add a little bit of click area inside the Table's checkbox cell
Users are reporting that misclicks are very common and often cause unwanted onRowClick effects, such as navigation.
You may visit [this link](https://artur--sandboxintegracao.myvtex.com/admin/suggestion/pending) to see this alteration in action. Clicking slightly below or above the checkbox will cause the line to be selected instead of calling the onRowClick navigation.
> Expand click area for table checkbox

- CHANGELOG.md
- manifest.json
- package.json
- react/components/ActionMenu/index.js
- react/components/Menu/index.js
1. `Menu` component uses `width` property and `DEFAULT_WIDTH` as fallback.
2. `ActionMenu` default `menuWidth` changed to `292` (same as `DEFAULT_WIDTH`), otherwise, it would always be the full width of the document body.
I needed a smaller `Menu` from `ActionMenu`, however, the `menuWidth` wasn't working.
1. `git checkout fix/action-menu-width`
2. `yarn start`
3. Go to [http://localhost:6060/#/Components/Forms/ActionMenu](http://localhost:6060/#/Components/Forms/ActionMenu)
4. Add the `menuWidth` property to any `ActionMenu`, change the size and check the results.
`menuWidth` set to `100`:
`menuWidth` set to `400`:
> ActionMenu width is constant

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Input/index.js
Prefixes and suffixes has a hard coded width. No more.
Fixes https://github.com/vtex/styleguide/issues/732
http://10.1.14.178:6060/#/Components/Forms/Input
> Fix prefix & suffix widths

- CHANGELOG.md
- manifest.json
- package.json
- react/components/ActionMenu/index.js
- react/components/Alert/index.js
- react/components/Menu/index.js
- react/components/Modal/TopBar.js
- react/components/Modal/index.js
- react/components/PageHeader/index.js
- react/components/Pagination/index.js
- react/components/Table/SimpleTable.js
- react/components/Table/index.js
Make Table work with FormattedMessage, prevent Menu, Alert, Page Header and Action Menu from emitting warnings when using FormattedMessage.
Table not being compatible with the use of FormattedMessage component. And Menu, Alert, Page Header and Action Menu were compatible but would fire a console error because of prop types.
Menu, Alert, Page Header and Action Menu and Table should work as before when using strings for props. And should work the same when using FormattedMessage as props.
There should be no console logs with "[Element] expected string but got object instead".
The behaviour of **sorted** headers when using Formatted Message has changed.
Before:
Now:
> Fix prop types strings

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/index.js
Here we will add a prop called `selectedRows` that contains the information about the selected items. If this prop is not `undefined`, then the selectedRows will be controlled outside the component(by the caller), if `undefined` the table will control the selected elements.
When you need to control the deselect some items in the table when an event happens, this is not possible with the current props.
1. Go to https://laercio--basedevmkp.myvtex.com/admin/suggestion/pending
2. Select some items using the bulk actions(1 one or more)
3. Then Choose `Approve as new product`
4. Close the modal(yes, just close it)
5. Then the items should be unselected.
> Adding prop and update the state when component updates

- react/components/Toggle/index.js
The buttons in the Table component that toggle the visibility of the columns have a bug where they don't work if you click a certain part of the button.
The button should respond to clicks in its whole area
> fix toggle onclick bug

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Layout/index.js
Fix the layout in admin pages with content smaller than the window height.
Currently, the `<Layout />` component uses `min-height: 100%` instead of `min-height: 100vh`. The `Layout` will only have the window height (100%) if its parent has a defined height, which it doesn't.
Just go to an admin page and change the class of a layout component to `min-vh-100`.
**Before**:
**After**:
> Replace min-h-100 with vh version

- CHANGELOG.md
- react/components/Toggle/index.js
The buttons in the Table component that toggle the visibility of the columns have a bug where they don't work if you click a certain part of the button.
The button should respond to clicks in its whole area
> Fix Toggle click area

- CHANGELOG.md
- manifest.json
- package.json
- yarn.lock
Fix the issue #775 
Updated the `react-responsive-modal` lib in the root package.json folder
The inStore, which uses the npm package, was receiving an old version of the `react-responsive-modal` which was different from the styleguide site.
Linking with npm and testing in the inStore, steps to reproduce in #775
> Fix mismatched versions of react-responsive-modal lib between the two package.jsons

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
To fix a bug in `Button` component.
When the prop `href` and `block` are used, the label is not horizontally aligned in center.
https://augusto--vtexgame1.myvtex.com/cart
Before:
After:
> Fix button link block

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
Add no upper case option to tertiary button.
Mimic the look of a link while still being a button for semantic purposes.
Checkout && `yarn styleguide`.
> Add noUpperCase prop

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
Prevent button labels from wrapping.
Checkout & `yarn styleguide`
Before:
After:
> Add nowrap class

- CHANGELOG.md
- manifest.json
- package.json
- react/components/DatePicker/index.js
It is necessary for the [PR #85](https://github.com/vtex/admin-collections/pull/85)
The `positionFixed` prop in the `DatePicker` component was using `boolean` instead of `bool` in the `propTypes`.
[Workspace](https://vitoria--storecomponents.myvtex.com/admin/collections/768/).
Not necessary.
> Fix invalid prop-type for the positionFixed prop in the DatePicker component

- CHANGELOG.md
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/Toolbar/InputCustom.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/index.tsx
To avoid blocking development, the table toolbar may receive a custom input.
It's important to notice that this feature will be deprecated when the `Autocomplete` is implemented.
`yarn start`?
No need
> Added InputCustom to Table V2

- CHANGELOG.md
- react/components/Button/index.js
- react/components/Radio/index.js
Fix radio circle position to items-start
Closes https://github.com/vtex/styleguide/issues/798
Radio circle was not positioned as the Figma component.
| Before| After|
|-|-|
|<img width="329" alt="Screen Shot 2019-08-29 at 11 51 44" src="https://user-images.githubusercontent.com/5608421/63951187-ae7c7880-ca53-11e9-8421-b7929b60547f.png">|<img width="362" alt="Screen Shot 2019-08-29 at 11 52 29" src="https://user-images.githubusercontent.com/5608421/63951204-b63c1d00-ca53-11e9-8be8-ba0493dbdb7f.png">|
> Fix radio circle position to items-start

- CHANGELOG.md
- manifest.json
- package.json
- react/Tooltip.ts
- react/components/Button/index.js
- react/components/Tooltip/Portal.tsx
- react/components/Tooltip/README.md
- react/components/Tooltip/TooltipPopup.tsx
- react/components/Tooltip/hooks.ts
- react/components/Tooltip/index.tsx
- react/components/Tooltip/tooltip.css
- react/components/Tooltip/utils/dom.ts
- react/components/utils/react.ts
- react/package.json
- react/yarn.lock
- styleguide.config.js
Add the `Tooltip` Component ✨ ([Figma's spec](https://www.figma.com/file/hXb2U8ARb4WgpE6LMXG92h/Componentes?node-id=0%3A1))
There was no tooltip component implemented on Styleguide
Clone this repo and run `yarn && yarn start`
> Add the Tooltip component

- CHANGELOG.md
- manifest.json
- package.json
- react/tsconfig.json
Fix tsconfig's module resolution, as we want it to catch the `index.tsx` files too.
Was not able to find the `./components/Tooltip` module but there was a `./components/Tooltip/index.tsx` file.
Clone this branch and run `yarn && yarn type-check`
> Fix tsconfig module resolution to be node and not classic

- CHANGELOG.md
- react/components/Table/BulkActions.js
- react/components/Table/README.md
Adding the isDangerous style of the line actions to the bulk actions.
Sometimes the bulk actions options are the same as the line actions'. So it makes sense for bulk actions to have isDangerous style as well. An example of use case is the "Reject SKU" option.
Go to https://enzo--partnerchallenge29.myvtex.com/admin/suggestion/pending, select 2 or more SKUs, then go in "More" to see the isDangerous style.
isDangerous style (red) on line actions:
Current state:
Proposed state:
> Adding isDangerous style of line actions to bulk actions

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
Fix a bug that breaks a loading button highlight
When a button used the prop `block`, its loading state displayed a bad highlight when clicked.
Click the loading button at:
https://rafaprtest--parceiro01.myvtex.com/_v/segment/admin-login/v1/login?returnUrl=%2Fadmin
> Fix button label escaping button

- CHANGELOG.md
- react/components/Input/Input.css
- react/components/Input/edge.css
- react/components/Input/index.js
- react/components/NumericStepper/index.js
Move the `appearance: none` from an inline style to a CSS class in the `Input` component.
In AMP pages, the prefix on the `appearance` property is prohibited, and renaming it to just `appearance` would probably make it not work in the browsers that only support the prefixed version, so moving it to a class and letting postcss add the prefix fixes the issue.
> Move appearance inline style to class

- CHANGELOG.md
- package.json
Closes https://github.com/vtex/styleguide/issues/823
A merge in 8.x would trigger a deploy of the Styleguide site with the 8x branch.
> Remove deploy task

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/SimpleTable/Loading.tsx
- react/components/EXPERIMENTAL_Table/SimpleTable/index.tsx
- react/components/EXPERIMENTAL_Table/errors.ts
- react/components/EXPERIMENTAL_Table/hooks/useTableContext.ts
- react/components/EXPERIMENTAL_Table/index.tsx
- react/components/EXPERIMENTAL_Table/typings.d.ts
The `EXPERIMENTAL_TableV2` is now able to show a loading spinner.
`yarn start`
> Added loading to EXPERIMENTAL_TableV2

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/BulkActions.js
To add the option to now show select all button on table's bulk actions.
Our API doesn't suport actions on all elements, so showing a "select all" button to the client is confusing. Also today then the bulk actions component doesn't receive some props it renders "undefined" on the action bar.
This link shows the table with no select all button
https://anita--basedevmkp.myvtex.com/admin/received-skus/pending
This link shows the button still working, also linked in this branch
https://anita2--basedevmkp.myvtex.com/admin/received-skus/pending
> Add option to not show select all button

- CHANGELOG.md
- manifest.json
- package.json
- react/components/MultiSelect/README.md
Fix errors in the **MultiSelect** documentation page.
Go to the **MultiSelect** docs page and the errors will be gone.
> Add import to deprecation Alert

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/SimpleTable/Header.tsx
- react/components/EXPERIMENTAL_Table/SimpleTable/Row.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonColumns.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonGroup.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/Menu/Box.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/Menu/Item.tsx
- react/components/EXPERIMENTAL_Table/constants.ts
- react/components/EXPERIMENTAL_Table/hooks/useHiddenColumns.ts
- react/components/EXPERIMENTAL_Table/hooks/useTableState.ts
- react/components/EXPERIMENTAL_Table/typings.d.ts
➕ `ButtonColumns` to `EXPERIMENTAL_TableV2`
The `Table v2` toolbar may toggle columns visibility.
`yarn start`?
> Add ButtonColumns to EXPERIMENTAL_TABLE_V2

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/Toolbar.js
Do not show columns in the show/hide column list if there is no text (trimmed) for that column (title or field name).
The following weird behavior:
> Do not show column for showing/hiding when there is to text

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Tooltip/TooltipPopup.tsx
- react/components/Tooltip/index.tsx
Fix the required tooltip measures. Now:
1. The default font size is `small`;
2. The offset (distance between the element and the tooltip) is now 8px instead of 16px;
3. Shadow is `shadow-4` instead of `shadow-1`.
Wrong measures.
Clone the repository, checkout to this branch and run `yarn && yarn styleguide`
> Fix Tooltip offset size, default font size and shadowing

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Input/index.js
Update readonly styles of input component.
Wrong styles.
Checkout and `yarn styleguide`
Before:
After:
> Fix readonly styles

- CHANGELOG.md
- manifest.json
- package.json
- react/components/RadioGroup/README.md
- react/components/RadioGroup/index.js
Also, updates the examples in the documentation so as to encourage usage of the component with the `hideBorder` ON.
> Removes unnecessary margins and paddings from hideBorder

- CHANGELOG.md
- manifest.json
- package.json
- react/modules/withForwardedRef.js
The `current` value of the `ref` prop is always undefined. Its value is only set when the DOM loads, so it doesn't make sense to be required.
The input is used [here](https://addskuerrormodal--storecomponents.myvtex.com/admin/app/collections/create), the ref is used to set the focus to the input when save is pressed and the name is not filled.
> Fix withForwardedRef propType

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/SimpleTable.js
Add a `preferentialSortOrder` option, defaulted to `ASC` (the previous hardcoded behaviour), which can be used by the developer to set the first sort order in a column sort click.
The Table component has a hardcoded preferential sort order set to `ASC`, i.e., on a sortable column header first click, the table order is automatically set to an ascending order.
However, in some applications, the most interesting numeric values in a sortable list are the larger ones, and in the current context, these are two clicks away from an unsorted state instead of one.
- Visit [this link](https://artur--sandboxintegracao.myvtex.com/admin/received-skus/approved/)
- Click in the `Price` or `Stock` column header. The first sort order will be descending, instead of the usual ascending. Further clicks in the …
> Add preferential sort order option to table

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/Toolbar/Button.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonNewLine.tsx
The button presentation should match the previous table.
`yarn start`
Before
After
> Fix EXPERIMENTAL_Table's ButtonNewLine presentation

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/SimpleTable.js
- react/components/Table/index.js
Add a `Dynamic Row Height` option to table v1.
Some applications require that the table height have a little flexibility. For example, for a list of SKUs, on a column with SKU names, it is very important that the names endings (which usually contain specifications information), are displayed. However, if said names are too long, they can be cropped or hidden from view, as shown in Figure 1.
Thus, by enabling a dynamic row height, we can provide a little bit more of space to cells that are meant to contain highly flexible content, as shown in Figure 2.
You can go to [this link](https://artur--sandboxintegracao.myvtex.com/admin/received-skus/approved/?elements=15&from=0&to=15) to see the change in action. Alternatively, you can test this by:
1. Pulling this branch in your project that uses …
> Add dynamic row heights to table

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
- react/components/Dropdown/index.js
- react/components/EmptyState/index.js
- react/components/Input/index.js
- react/components/PageBlock/index.js
Add simple data attribute `testid` to prevent developers from adding an extra html element around the element to be tested. Usually via e2e tests.
Closes https://github.com/vtex/styleguide/issues/848
Checkout & add the attribute `testId` to one of the following components:
- `Input`
- `Dropdown`
- `EmptyState`
- `Button`
- `PageBlock`
> Add data-testid attribute

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Input/index.js
- react/components/Textarea/index.js
- react/components/Toggle/index.js
Allow the users to use the input properly and allow inputs which have tooltips.
[workspace](https://rerisson--storecomponents.myvtex.com/admin/brand/create/)
These inputs are from styleguide.
> Fix PropTypes for Input, TextArea and Toggle

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Tooltip/TooltipPopup.tsx
The tooltip was getting positioned wrongly in the admin `brand` page. `document.body.offsetHeight - top` was negative so the `translate3d` didn't work properly.
Tooltip wrongly positioned.
[Working workspace](https://categories--storecomponents.myvtex.com/admin/brand/2000000/)
> Fix Tooltip popup's position

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/BulkActions.js
- react/components/Table/SimpleTable.js
- react/components/Table/index.js
- react/package.json
- react/yarn.lock
Add an option to make the Bulk Actions bar sticky, so that a long selection of rows can maintain the bulk actions visible while the user scrolls to the bottom of the table it is associated with.
Long table lists tend to hide the bulk actions bar when the user is scrolling down.
You can check the proposed feature in this [running workspace](https://artur--partnerchallenge26.myvtex.com/admin/received-skus/pending). Or if you want to check this out manually, you may
1. Pull this branch and link the app.
2. Make a table with a considerable amount of lines and, in your `bulkActions` options, use `fixed: true`.
None
> Add `fixed` option to make Bulk Actions bar sticky

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/index.tsx
- react/components/EXPERIMENTAL_TableTree/README.md
- react/components/EXPERIMENTAL_TableTree/Tree/CellPrefix.tsx
- react/components/EXPERIMENTAL_TableTree/Tree/TreeHeadings.tsx
- react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
- react/components/EXPERIMENTAL_TableTree/contexts.tsx
- react/components/EXPERIMENTAL_TableTree/index.tsx
The `TableTree` may work without checkboxes.
Clone the repo and: `yarn && yarn start`
WIP
> Fix: Table tree not rendering if checkboxes are not allowed

- CHANGELOG.md
- manifest.json
- package.json
- react/components/FilterBar/index.js
It's not a required prop, so it needs a `defaultProp` or a safe usage. `defaultProps` are more elegant.
When not passing the `statements` prop, the component breaks.
To see the problem:
- Access the [Styleguide](https://styleguide.vtex.com/#/Components/Display/FilterBar)
- Edit one of the examples and delete a `statements={something}` statement in the component declaration.
> Fix FilterBar statements defaultProps

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Select/index.js
To fix a warning being shown when passing an array of options as the `defaultValue` of a `Select` component
Testing on this [link](https://kiwi--recorrenciaqa.myvtex.com/admin/tracking-apps/vtex.totalexpress-tracking-integration/). Just click on `edit`.
Warning before:
Warning after:
~no image because there's no warning anymore 👀~
> Make Select accept an array of options as the defaultValue

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Statement/Atoms/ObjectAtom.tsx
- react/components/Statement/Atoms/VerbAtom.tsx
- react/components/Statement/index.tsx
As the title says. When there is only one option, it should show a `span` tag instead of a `Select` option.
Clone the repository, checkout to this branch and run `yarn && yarn styleguide`.
> Fix verb atom behavior when there's only one option

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/BulkActions.js
- react/components/Table/SimpleTable.js
- react/components/Table/index.js
- react/package.json
- react/yarn.lock
1. Change condition for checking SSR condition in Simple Table to `typeof document === 'undefined'` which is ReferenceError safe for `document`.
2. Change usage of `react-stickynode` library for `react-sticky`, which is
SSR-friendly.
This should address issues #746 and #894.
- [Running workspace](https://artur--partnerchallenge26.myvtex.com/admin/received-skus/pending) with a sticky Bulk Actions bar in action
- [Running workspace](https://artur--partnerchallenge26.myvtex.com/test) with a SSR-rendered table
1. Current checking with `!document` yields a Reference Error in SSR, since this global variable is not defined outside the browser--no DOM references. Thus, a safer approach is to use `typeof` which evaluates any symbol, even undeclared variables.
2. Since `react-stickynode` evaluated …
> Fix Table v1 SSR errors

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/index.js
Change condition for checking SSR condition in Table to `typeof document === 'undefined'` which is ReferenceError safe.
_This should address issues #746 and #894 for Styleguide 8.x_
[Running workspace](https://artur--partnerchallenge26.myvtex.com/test) with a SSR-rendered table in Render 7.x
Current checking with `!document` yields a Reference Error in SSR, since this global variable is not defined outside the browser--no DOM references. Thus, a safer approach is to use `typeof`, which evaluates any symbol, even undeclared variables.
You can visit the link provided above
None
> [8.x] Fix SSR checking in Table

- CHANGELOG.md
- docs/developing.md
- manifest.json
- package.json
Mention that manually adding the `vtex-tachyons` dependency is required to get the styles of the components that are seen in the documentation.
Closes #723.
[Running workspace](http://10.1.14.209:6060/#/Introduction/Developing)
> Add vtex-tachyons mention in non-io docs

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Conditions/README.md
- react/components/Conditions/index.tsx
- react/components/EXPERIMENTAL_Select/README.md
- react/components/EXPERIMENTAL_Select/index.js
- react/components/Statement/Atoms/ObjectAtom.tsx
- react/components/Statement/Atoms/SubjectAtom.tsx
- react/components/Statement/Atoms/VerbAtom.tsx
- react/components/Statement/index.tsx
- react/components/Statement/typings.d.ts
Allow developers to group their conditions subjects.
When we had too many subjects it was really hard to find the wanted option. Sometimes we had to use a part of the subject in the verb to overcome this problem (see the image below for an example).
[Running workspace](http://10.1.14.209:6060/)
> Allow grouping conditions subject

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Collapsible/index.js
- react/components/Modal/TopBar.js
The prop `title` (`Modal` component) gets a node, usually it is only a short text, but can be a component. 
I needed to use the `InputSearch` component in Modal title 
but I couldn't expand input because of width from TopBar title. 
Adding width: 
(look at  **Off-Road & All-Terrain Vehicle Protective Gear**)
When the text has a line break the arrow icon stay in the div center. 
I needed to put the icon align with Radio and text. To be like that: 
So, my idea was create a prop ( `arrowAlign`)  which allows you decide the icon position. 
The position could be `start`, `center`, `end`, `baseline` or `stretch`.  
And if you don't use the prop `arrowAlign`, the icon position will be `center`. 
Clone the repository, checkout to this branch and run yarn && …
> Add width style on Modal TopBar title and fix arrow align on Collapsible

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/SimpleTable.js
- react/components/Table/index.js
To add an optional prop `onRowHover` to table
To allow devs to take action when some line is hovered, like specific changes to some cells in the hovered row.
The motivation comes from our team designer wanting some buttons to pop up only when the row is hovered.
https://anita--partnerchallenge26.myvtex.com/admin/received-skus/pending/ has an example of a table using onRowHover
click on the "Approved" tab and see another table, this time without `onRowHover`, still working properly.
> Add optional onRowHover prop to table

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/CheckboxContainer.js
To remove an unnecessary error/warning from the console.
Whenever someone uses table with bulk actions and then selects some line this error pops up
This happens because theres is a container around the checkbox and it doesn't really need an `onChange` prop, ever.
yarn test
> Fix checkbox onChange warning

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Tooltip/TooltipPopup.tsx
- react/components/Tooltip/index.tsx
Tooltip wasn't working with SSR because the constructor `HTMLElement` only exists in the browser.
The page that use SSR and the `Tooltip` was crashing
[Running workspace](https://skuinitial--storecomponents.myvtex.com/classic-shoes/p)
Access this [workspace](https://skuinitial--storecomponents.myvtex.com/classic-shoes/p) to see working
Go to [this one](https://crashingssr--storecomponents.myvtex.com/classic-shoes/p?) to see the error
> Fix Tooltip usage with SSR

- CHANGELOG.md
- package.json
- react/components/Input/index.js
- react/components/InputButton/README.md
- react/components/InputButton/index.js
To allow a loading status to `InputButton` component.
`InputButton` don't have a way to give feedback when, after submitting the form, something needs to load and the user needs to wait.
http://localhost:6060/#/Components/Forms/InputButton
> Add loading status to InputButton

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/hooks/useTableBulkActions.tsx
- react/components/EXPERIMENTAL_Table/index.tsx
- react/components/EXPERIMENTAL_TableTree/README.md
- react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
- react/components/EXPERIMENTAL_TableTree/hooks/__tests__/checkboxesUtils.test.ts
- react/components/EXPERIMENTAL_TableTree/hooks/checkboxesUtils.ts
- react/components/EXPERIMENTAL_TableTree/hooks/useTableTreeCheckboxes.tsx
- react/components/EXPERIMENTAL_TableTree/index.tsx
➕Added `comparator` prop.
➖Remove `unicityKey` prop.
Sometimes, items could not have a single prop that makes them unique. To solve the issues that may be caused by it, the prop `unicityKey` was deprecated in favor of a `comparator` function. 
This curry function should return true if the unique constraint is fulfilled, and its default value is:
`item => candidate => item.id && candidate.id && item.id === candidate.id` (items are equal if their id is the same).
Clone the repo and `yarn start`. [Running workspace](https://matheusps--storecomponents.myvtex.com/admin/collections/)
> Experimental Table: Handle items unicity using comparator function

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_TableTree/README.md
- react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
- react/components/EXPERIMENTAL_TableTree/hooks/useTableTreeCheckboxes.tsx
- yarn.lock
The arrow must not be shown when nodesKey is an empty array.
Clone the repo and `cd styleguide && yarn && yarn start`
> Fix: EXPERIMENTAL_TableTree shows arrow with empty nodesKey

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/SimpleTable.js
Recalculate table container height after cell rendering.
On every first rendering of the **Table v1**, while using the `dynamicRowHeight` option, we encounter a bug in which the table's initial height is set to the default height set by its density, and then a forced update (like a user interaction with the table) is needed in order to make the table's height be the sum of the individual rows' heights.
This happens because, when using `SimpleTable`'s `calculateContainerHeight` on the render method, we failed to notice that in order to correctly calculate the height needed to fit the cell content into it, it was first necessary to let the rendering occurr, and then measure each individual cell height. Before that, the height needed for each cell is not even defined to begin with. …
> Update table height after rendering

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/README.md
- react/components/Table/SimpleTable.js
Add an `updateCellMeasurements()` callback to the provided props in `skuCellRenderer`.
While the table height is being updated whenever there is a different *sum* of rows heights, sometimes the individual cell height is not being updated in the cell measurement cache, causing said sum to convey the wrong height measurement for the table.
Since this depends on some obscure logic for the CellMeasurer cache that maintains the cell previous measurements, one way of refreshing those measurements is to provide the `measure()` render prop provided by the `CellMeasurer`. That way one can programatically remeasure an individual cell and update the entire row.
This is similar to the `react-virtualized` recommended approach for cells that contain images, [which can be seen …
> Provide updateCellMeasurements() method for cell height refresh

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/hooks/useTableBulkActions.tsx
- react/components/EXPERIMENTAL_Table/hooks/useTableVisibility.ts
- react/components/EXPERIMENTAL_Table/index.tsx
- react/components/EXPERIMENTAL_TableTree/README.md
- react/components/EXPERIMENTAL_TableTree/Tree/TreeHeadings.tsx
- react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
🛠 Names of `cellRender` and `headerRender` in favor of `cellRenderer` and `headerRenderer` on `EXPERIMENTAL_Table`.
➖ Remove `hidden` prop from `Column`.
The `columns` section needed better documentation and the `stateHook` is deprecated.
`yarn start`
> Better table columns and documentation

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Progress/Line.tsx
Fix width of progress type line
Progress type line do not render if your parent is a flex element
Access the styleguide locally in Progress section
> fix width of progress type line

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
- react/components/EXPERIMENTAL_TableTree/README.md
- react/components/EXPERIMENTAL_TableTree/Tree/CellPrefix.tsx
- react/components/EXPERIMENTAL_TableTree/Tree/CollapseToggle.tsx
- react/components/EXPERIMENTAL_TableTree/Tree/TreeHeadings.tsx
- react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
- react/components/EXPERIMENTAL_TableTree/index.tsx
🛠Fixed alignment between checkboxes and carets.
🛠Reduced carets size
➕Added `onRowClick` prop to `EXPERIMENTAL_TableTree`
➕The `EXPERIMENTAL_TableTree` collapses on click the first cell
The table tree must have a consistent design.
Before
After
> Table Tree UX Improvements

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/BulkActions.tsx
- react/components/EXPERIMENTAL_Table/hooks/useTableBulkActions.tsx
In the `ProductsTable` of the `admin-collections` we need to use the bulkActions without set any action to it, according to the design as you can see bellow. For now, if the main and the other actions are not set, the component does not appear.
Run the following command and access the `http://localhost:6060/`:
```
yarn start
```
Or access the [workspace](https://waza--storecomponents.myvtex.com/admin/collections/1103/).
> Show EXPERIMENTAL_BulkActions even if no action is set

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_TableTree/Tree/CellPrefix.tsx
[Running workspace](https://vitoria--storecomponents.myvtex.com/admin/collections/1094/)
Clone the repo and `yarn & yarn start`
Before
After
> Fix checkbox alignment when there is no arrow in the EXPERIMENTAL_TableTree

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_TableTree/README.md
This change is to avoid the other columns to "jump" when the first collapse.
Before:
After:
> Fixed first column width of EXPRIMENTAL_TableTree docs

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/Toolbar/Button.tsx
[Running workspace](https://exportcolprods2--storecomponents.myvtex.com/admin/app/collections/create)
Check that the color of the export button is different because it is disabled.
> Set color to c-muted-2 when toolbar button is disabled

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Pagination/PageIndicator.js
- react/components/Pagination/index.js
- react/components/Table/SwitchablePagination.js
- react/components/Table/index.js
Add a page top indicator option to the `Pagination` component
Some pages have content that are so large that the reference of which page is being displayed is lost to the immediate view.
To fix this, add an option to the pagination component in which a page indicator is shown above the content in such a way that the paginated nature of a search result is easier to perceive.
You can [visit this link](https://artur--partnerchallenge26.myvtex.com/admin/received-skus/approved/?elements=15&from=0&to=15) to see an example of a table using the proposed feature
> Add page top indicator option to Pagination

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Charts/LineChart/README.md
- react/components/EXPERIMENTAL_Charts/LineChart/constants.ts
- react/components/EXPERIMENTAL_Charts/LineChart/helpers.ts
- react/components/EXPERIMENTAL_Charts/LineChart/index.tsx
- react/components/EXPERIMENTAL_Charts/LineChart/multilineSample.js
- react/components/EXPERIMENTAL_Charts/commonProps.ts
- react/components/EXPERIMENTAL_Charts/helpers.ts
- react/components/EXPERIMENTAL_Charts/typings.d.ts
as the title says.
- Allows hide the chart axis
- Allows different configs for the `xAxis` and `yAxis`
- Allows different interpolations of the chart
- Allows that the axis label would be changed
- Improve the docs, to include charts for show how can we change the atributtes
- Make Line Chart Responsible, now the container, for default, auto-adjust for the size of the screen :tada: 
- Change `schema` to `config` prop
`yarn install` && `yarn start`
> Update Line Chart Props

- CHANGELOG.md
- manifest.json
- package.json
- react/EXPERIMENTAL_useTableProportion.ts
- react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/hooks/useTableProportion.ts
- Add useTableProportion hook.
- Solve cell bugs.
⚠️ The detailed documentation will be present on #953 
You can consider this hook a shorthand for setting columns width based on a passed ratio array.
This represents the ratio `[3,1]`. This means that the first column will grow three times more than the second.
If we want to divide equaly, just  set 1 to every col `[1,1]`
⚠️ The proportions respect the `truncate of rows`. This means that doesn't matter how large one ratio is compared to other ones - the content will **NOT** break by `default`. In the screenshot below you can see the ratio `[100, 1]`.
> Added useTableProportion hook

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/index.js
Fix lack of space between the Totalizer and the table.
> Fix totalizer margin

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/index.js
Update prop.
Totalizers in Table were only allowing an array for the totalizer items. Now it accepts both array and shape.
> Update totalizers prop

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Progress/Steps/index.js
- react/components/Radio/index.js
Progress `steps` prop is not required if progress type is line. As the line progress and steps progress props are merged, a better way of handling it is not making it required at all (but if you have any other suggestion its really welcome).
It also fixes the prop `isLast` of the radio component.
Click `Export` and select any format. Check that no warning is shown about the progress.
Try opening the `import` modal. Check that no warnings are shown for the radio.
[Workspace with error](https://tsmaststyle--storecomponents.myvtex.com/admin/app/collections/1112)
[Fixed workspace](https://exportcolprods2--storecomponents.myvtex.com/admin/app/collections/1112)
> Fix proptypes

- CHANGELOG.md
- manifest.json
- package.json
- react/components/AutocompleteInput/Option.tsx
- react/components/AutocompleteInput/index.tsx
Remove the key prop from the option button.
The key is already defined [here](https://github.com/vtex/styleguide/blob/422a40f7c9715a6bcd45578e18de50f22e7bd0e1/react/components/AutocompleteInput/index.tsx#L160)
The key only needs to be defined in the upper level component
> Remove key from option

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/index.tsx
The `headerRenderer` property was deprecated because didn't make a lot of sense based on how the table is being used. Now the title either receives a string or element.
clone the repo and `yarn && yarn start`
No need.
> Simplify columns API of EXPERIMENTAL_Table

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/sampleData.ts
- react/components/EXPERIMENTAL_useCheckboxTree/README.md
- react/components/EXPERIMENTAL_useCheckboxTree/__tests__/util.test.ts
- react/components/EXPERIMENTAL_useCheckboxTree/constants.ts
- react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
- react/components/EXPERIMENTAL_useCheckboxTree/reducer.ts
- react/components/EXPERIMENTAL_useCheckboxTree/types.ts
- react/components/EXPERIMENTAL_useCheckboxTree/util.ts
- styleguide.config.js
- Allow checkboxes to be disabled
- Added dedicated docs for checkbox trees.
- Added `setChecked` function.
> Control checkbox disable state on EXPERIMENTAL_useCheckboxTree

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Dropdown/index.js
- react/components/Input/index.js
- react/components/NumericStepper/index.js
This PR fix a strange behavior in iPhones. When focusing on form elements, like `input`, the page is zoomed in, because of the text size (14px). It's the default behavior for elements with text size smaller than 16px.
Fixing that, the size of that elements will be consistent with the base text size of the page.
1. Take yout iPhone
2. Add this product to Cart: https://www.madinejeans.com.br/jogger-feminina-saruel/p
3. Click in "Aplicar cupom de desconto"
4. Repeat steps 2 and 3 with this product: https://newinput--gc-jqu0734.myvtex.com/jogger-feminina-saruel-38/p and check the difference.
**Before**
**After**
> Change default sized form elements text size to t-body

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Box/index.tsx
- react/components/PageBlock/index.js
Allow the Box component in Layout to receive either the `noPadding` or `title` prop.
On mobile cases we will need to reset/redefine the padding of the Box component.
https://kevin--recorrenciaqa.myvtex.com/admin/orders-admin
> Add Box props to Layout

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
Fix the dependency array in the `toggleAll` function, preventing it from using stale values.
When you called `toggleAll` after changing the `items` parameter, the function was using stale values due to the function not being updated.
[Workspace](https://lucas--cosmetics1.myvtex.com/admin/app/collections/350/)
> Fix useCheckboxTree using stale values

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonGroup.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/InputSearch.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/index.tsx
Make toolbar items wrap on small screens, avoiding items to overflow.
When the toolbar has to many items it's causing the toolbar to overflow the table.
**Before**
**After**
> Fix EXPERIMENTAL_Table toolbar responsiveness on mobile

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
- react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
When all checkboxes are disabled, the heading 'check all' checkbox doesn't have any effect, so it should be disabled too.
[Running workspace](https://thay--cosmetics1.myvtex.com/admin/collections/628/)
The checkbox next to 'description' should be disabled.
> [EXPERIMENTAL_Table] Auto disable checkbox heading when all checkboxes are disabled

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
Add a missing handle to the label of the Button
[Running workspace](https://buttonhandle--storecomponents.myvtex.com/)
The agencies want to style the label of the Button, but with the new styles builder they can't do `.vtex-button span` because we don't allow to style direct elements, so we need to add classes to all elements of the store.
Before:
Now:
> Add missing handle to the label of the Button

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Conditions/Atoms/ObjectAtom.js
- react/components/EXPERIMENTAL_Select/index.js
Check the use of the prop in the `Status` filter.
[workspace using new prop](https://addactivefilter--storecomponents.myvtex.com/admin/app/collections/1164/)
[workspace not using new prop](https://addactivefilter1--storecomponents.myvtex.com/admin/app/collections/1164/)
*Before*
*After*
> Allow the use of defaultMenuIsOpen in EXPERIMENTAL_Select

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Statement/index.tsx
Fix an error caused when deleting a filter tag in the `FilterBar` component 
Deleting a filter tag in the `FilterBar` component can generate an error
[Running workspace](https://filtertag--cosmetics1.myvtex.com/admin/collections/create/)
Just follow the steps shown bellow in the usage example.
> Fix error when deleting a filter tag applied in the FilterBar component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/NumericStepper/index.js
To solve the same problem of https://github.com/vtex/styleguide/pull/997, but to the `NumericStepper` this time.
[Running workspace](https://numericstepper--alssports.myvtex.com/pat25450/p)
Before (the selected element is when the numeric stepper elements start):
After (the selected element is when the numeric stepper elements start):
> Add missing handles from NumericStepper

- CHANGELOG.md
- manifest.json
- package.json
- react/components/NumericStepper/index.js
- react/components/ToastProvider/README.md
- react/components/ToastProvider/Toast.js
- react/components/ToastProvider/ToastManager.js
- yarn.lock
Insert any name for the collection and click save repeatedly
Just using the button, nothing should be functional
[without keepAfterUpdate option](https://withoutop--cosmetics1.myvtex.com/admin/collections/create/)
[with keepAfterUpdate option](https://withop--cosmetics1.myvtex.com/admin/collections/create)
> Add option to keep toast open after update of its content

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonDensity.tsx
- react/components/EXPERIMENTAL_Table/hooks/useTableMeasures.tsx
- react/components/EXPERIMENTAL_Table/index.tsx
- react/components/EXPERIMENTAL_TableTree/README.md
- react/components/EXPERIMENTAL_TableTree/Tree/Node.tsx
- react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
- react/components/EXPERIMENTAL_TableTree/index.tsx
Renames:
🖥 Density: from `low`, `medium`, `high` ➡️`comfortable`, `regular`, `compact`.
🛠 `selectedDensity` ➡️`currentDensity`
[Running workspace](https://densitynames--cosmetics1.myvtex.com/admin/collections/)
Before:
After:
> Changed EXPERIMENTAL_Table density names

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/Toolbar.js
The default size of the `SearchInput` of the Styleguide Table's toolbar is different from the other Buttons of the toolbar.
Toolbar buttons default sizes incoherence. 
Resolves #990 
Checkout to this branch and look at the exemples with a toolbar like the above
> Toolbar buttons default size

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/ActionBar.tsx
- react/components/EXPERIMENTAL_Table/BulkActions/index.tsx
- react/components/EXPERIMENTAL_Table/FilterBar.tsx
- react/components/EXPERIMENTAL_Table/Pagination.tsx
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/Toolbar/index.tsx
- react/components/EXPERIMENTAL_Table/Totalizer.tsx
- react/components/EXPERIMENTAL_Table/constants.ts
- react/components/EXPERIMENTAL_Table/index.tsx
Better docs descriptions are being made on another PR, so do not worry about it 😅.
The table users may need to add custom bars. The order of the existing bars is granted, though.
> Added ActionBar to EXPERIMENTAL_Table

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Tooltip/TooltipPopup.tsx
The `Tooltip` container was appearing in the DOM even if its children are not `onHover`.
[Running workspace](https://vitoria--cosmetics1.myvtex.com/admin/collections/1014/).
Pass the mouse over the line action buttons in the products table.
In this usage, the click area of a button is reduced when we pass the mouse over another button bellow it because the tooltip container is above it even when it is not appearing.
> Fix Tooltip display verification logic

- CHANGELOG.md
- manifest.json
- package.json
- react/components/ToastProvider/Toast.js
Change `Toast`'s `keepAfterUpdate` prop type to boolean
[Control workspace](https://anita--sandboxintegracao.myvtex.com/admin/sellers/planilha/)
[Running workspace](https://artur--sandboxintegracao.myvtex.com/admin/sellers/planilha/)
This addresses a warning that appears whenever `showToast` is used
**Control**
1. Visit the control workspace and open your browse's Dev Tools
2. Click on the pencil icon at the upper right corner
3. Click `save` at the modal's bottom right corner
4. Watch the console. A toast-related warning about `keepAfterUpdate` should appear
**Fixed**
1. Visit the running workspace and open your browse's Dev Tools
2. Click on the pencil icon at the upper right corner
3. Click `save` at the modal's bottom right corner
4. Watch the console. No toast-related warnings should …
> Change Toast's keepAfterUpdate propType to bool

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/index.tsx
[Running workspace](https://matheus--cosmetics1.myvtex.com/admin/collections/) (click on a collection and check the products table)
The Table should have the support to highlight rows on `:hover`, even if they are not clickable.
```js
import { EXPERIMENTAL_Table } from '@vtex.styleguide'
const columns = [...]
const items = [...]
function UseCase(){
// ...
return <Table columns={columns} items={items} highlightOnHover />
}
```
> Added the highlightOnHover prop to EXPERIMENTAL_Table

- CHANGELOG.md
- manifest.json
- package.json
- yarn.lock
Updates the `react` and `react-dom` dependency (for development) and adds them as peerDependencies.
When you import styleguide in a normal react app, you may get the following error:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```
I believe this is due to react not being present in the peerDependencies, so when webpack compiles this to publish on NPM it insert it's own copy of React in the package, making …
> Update react dependency and add as peer

- CHANGELOG.md
- manifest.json
- package.json
- yarn.lock
Moves the `postinstall` script to the [`prepare`](https://docs.npmjs.com/misc/scripts#prepublish-and-prepare) script, since it's more appropriate.
This is to avoid adding the dev dependencies of this package in production environments, which also breaks React Hooks because styleguide will be using it's own version of React, which will be different than the one used in the application importing it.
Create a sample react project with
```
yarn create react-app styleguide-test
cd styleguide-test
```
Then, add this version of styleguide and verify if any component that uses hooks is rendering correctly. **It is important to *not* run `yarn` on the styleguide directory, as it will always bring the node_modules folder when you locally `yarn add` it.**
```
yarn add ../path/to/styleguide
yarn …
```
> Move postinstall script to prepare script

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Input/Input.css
- react/components/Input/index.js
Add a `input` css class/handle to the `Input` component
[Running workspace](https://kiwisearch--storecomponents.myvtex.com/)
Just check the search bar input on the header of the workspace above
> Add input css handle

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Cell.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
- react/components/EXPERIMENTAL_Table/DataTable/index.tsx
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/hooks/useTableMotion.ts
- react/components/EXPERIMENTAL_Table/index.tsx
The Table headers can be fixed for a better viz when the items list is large.
This PR also removes the possibility of passing different elements then `td`, `th`, `tr` or `table`. This is to grant accessibility.
> Added sticky header to EXPERIMENTAL_Table

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Cell.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
As title says
[Running workspace](https://wksquebrada--cosmetics1.myvtex.com/admin/app/collections/1349/)
After [the sticky-header pr](https://github.com/vtex/styleguide/pull/1047) the backgrounds do not work as intended because of `bg-base
`. This PR fixes it.
Now:
After Changes:
> Fixed EXPERIMENTAL_Table background colors

- CHANGELOG.md
- react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
The color of a secondary button clicked should be `#DBE9FD (light blue)`
[Running workspace](https://mariana--cosmetics1.myvtex.com/admin/collections/1019/)
* Before: 
* After:
> Fix highlight color of a selected row

- CHANGELOG.md
- react/components/EXPERIMENTAL_Select/index.js
Fix unwanted focus on `EXPERIMENTAL_Select`.
After options were loaded (usually receiving a prop update setting `loading = false`, component forced focus on its input. So, when you open a page with a select, it may scroll and focus on it right after finishing options load. We only want it to keep focused while searching.
old version: https://pricingqa.myvtex.com/admin/promotions/0980ee34-349b-48fa-98b9-3702c4f18ba3
current version: https://vlauxbeta--pricingqa.myvtex.com/admin/promotions/0980ee34-349b-48fa-98b9-3702c4f18ba3
> Keep input focused only while searching

- CHANGELOG.md
- react/components/Table/SimpleTable.js
As title says.
When there is a column without width defined (meaning it should use the available width), after content is loaded and a scrollbar appears (in case it does), the column size is not updated and a gap remains between them. Only happens when full width is used.
Before: https://pricingqa.myvtex.com/admin/promotions
Now: https://vlauxbeta--pricingqa.myvtex.com/admin/promotions
> Remove gap between columns when scrollbar appears

- CHANGELOG.md
- manifest.json
- package.json
- react/components/FilterBar/FilterTag.js
The filter tag is not closing when filter is cleaned.
[Running workspace](https://thay--cosmetics1.myvtex.com/admin/collections/1022/)
**Before**
**After**
1. Select a filter and apply
2. Open the filter
3. Click on clear and see if the filter will close.
> fix filter tag not closing when filter is cleaned

- CHANGELOG.md
- manifest.json
- package.json
Generating lib folder and publishing in beta to test.
in version `@vtex/styleguide@1.112.7` the lib folder was not generated
installing via npm
```cli
yarn add @vtex/styleguide@beta
```
> Fix version 1.112.7 in NPM

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Input/index.js
- react/components/InputButton/index.js
Currently, the `InputButton` styleguide component does not allow you to pass props to the button it renders. The reason for this is that the component was meant to be inside of a `form`, however, the `Location Field (Input)` Place Component needs to render a `InputButton` without the context of a form, since that component in itself can be embedded into another form, which would create a form inside of a form.
The solution is to provide a way to add props to this button, so that one can pass actions like `onClick` to it, in such a way that you don't need a wrapper form to use the component.
The component is being used under the "LocationInput" title.
[Workspace](https://locinput--checkoutio.myvtex.com/places)
> Adds `buttonProps` properties to `Input` and `InputButton`

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/Toolbar.js
As discussed on previous [Styleguide meeting](https://www.notion.so/Table-loading-state-disabling-ALL-buttons-ef37023799ab4a4dbf329a3db6954a54
), we don't want to disable search field and "new" button while loading table's content anymore.
[Running workspace](https://vlauxbeta--pricingqa.myvtex.com/admin/promotions)
> Do not disable new button and search while loading table's content

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/hooks/useTableVisibility.ts
[Running workspace](https://vitoria--cosmetics1.myvtex.com/admin/collections/2335/)
When using the `showAllColumns` of the `EXPERIMENTAL_useTableVisibility`, the maximum deph update was reached.
> Add useCallback in the EXPERIMENTAL_useTableVisibility to avoid always updating

- CHANGELOG.md
- react/components/Table/README.md
- react/components/Table/SimpleTable.js
To make possible the usage of the `headerRenderer` even when column options such as `sortable` and `fixFirstColumn` are enabled.
When either of `sortable` or `fixFirstColumn` are enabled, the column stops using the `headerRenderer` option and uses the default `title` instead.
[Here](https://artur--sandboxintegracao.myvtex.com/admin/sellers/?sortOrder=ASC&sortedBy=name) is an example of a Table with a sortable column that also uses a header renderer
> Enable headerRenderer usage in all header options

- CHANGELOG.md
- react/components/Input/index.js
issue: #938 
Use an input and pass an errorMessage prop
**before**
**after**
> Add warning icon when input has errorMessage

- .eslintrc
- config/env.js
- config/jest/fileTransform.js
- config/polyfills.js
- config/test.js
- config/webpack.config.js
#trivial Fix eslint errors #1082
Fix eslint in config folder
`yarn lint`
> Fix eslint in config folder

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Dropdown/Dropdown.css
- react/components/Dropdown/index.js
- react/components/Input/index.js
Adds a better support for the `Dropdown` component inside an `Input` prefix or suffix.
[Running workspace](https://lucas--checkoutio.myvtex.com/checkout/?cultureInfo=pt-BR#/profile)
With this, implementing the following design is more straightforward and requires no "hack" in userland.
> Fix Dropdown usage inside an Input prefix or suffix

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Dropdown/index.js
The variable was being accessed before definition.
clone the repo and `yarn && yarn start`
> [FIX] RefError by accessing 'valueLabel' const on Dropdown

- .github/CONTRIBUTING.md
Due to several problems that have been happening with the release, we have created a new contribution policy. 
The idea is that you don't have to worry about releasing, it will be done by people from the core team. 
> New changelog entries to the Unreleased section are still required in pull requests
> CONTRIBUTING

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Dropdown/index.js
[This PR](https://github.com/vtex/styleguide/pull/1087) removed the spacing for the large variation of the `Dropdown` and we really miss them. I rather use the same spacing as the other sizes as well.
Check the large variation here https://styleguide.vtex.com/#/Components/Forms/Dropdown
https://augusto--mystore.mygocommerce.com/admin/app/marketing/promotions/create
> Add inner spacing to large dropdowns

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Tooltip/TooltipPopup.tsx
- react/components/Tooltip/index.tsx
[clubhouse](https://app.clubhouse.io/vtex/story/31018/ui-implementation-resolver-problema-do-tooltip-quebrando-na-tabela-de-produtos)
[story related](https://app.clubhouse.io/vtex/story/30998/corre%C3%A7%C3%B5es-das-colunas-e-tooltips-na-tabela)
In this [workspace](https://lucasan2--cosmetics1.myvtex.com/admin/collections/) go to a collection page and on the second page of the product table you will see the example shown below
> Fix the tooltip overflowing with long words

- react/components/Input/index.js
- react/components/InputCurrency/index.js
- react/components/InputPassword/index.js
- react/components/InputSearch/index.js
eslint fixes for: `Input`, `InputCurrency`, `InputPassword` & `InputSearch` #1082
> #trivial : fix inputs eslint issues

- CHANGELOG.md
- manifest.json
- package.json
- react/components/AutocompleteInput/Option.tsx
Type `veg` in the products autocomplete input
[workspace](https://fixautocompletetext--cosmetics1.myvtex.com/admin/app/collections/2340/)
Before
After
> Fix AutocompleteInput styles

- CHANGELOG.md
- react/components/Progress/README.md
- react/components/Spinner/README.md
In the related components section of the [Spinner documentation](https://styleguide.vtex.com/#/Components/Display/Spinner) there's an outdated link to _ProgressBar_ (which is now called _Progress_). Also, there are references to the old name of the component in its [own docs page](https://styleguide.vtex.com/#/Components/Display/Progress).
> #trivial: Fix outdated link and references to ProgressBar in docs

- CHANGELOG.md
- react/components/Button/index.js
Fix outline of ButtonGroup.
Underlapping outline.
Before:
After:
> Fix outline on ButtonGroup

- CHANGELOG.md
- react/components/EXPERIMENTAL_Select/index.js
Allow user to customize compositional react-select components (as discussed in the weekly design meeting)
In some specific cases, there is a need to customize the react-select compositional components. To allow this, we need to spread the `component` prop received to `react-select`.
Use case: on the new promotions admin, there is a specific select were we just want to show a short version of the label in the option tag.
> Spread react-select props

- CHANGELOG.md
- react/components/EXPERIMENTAL_Table/Sections/Row.tsx
- react/components/EXPERIMENTAL_Table/Sections/Thead.tsx
- react/components/EXPERIMENTAL_Table/hooks/useTableSort.ts
Remove the onClick event of the `Table V2` header and allow user to set initial sorting state.
Sort the collections by their id:
[workspace](https://sortableid--cosmetics1.myvtex.com/admin/app/collections/)
> Fix table v2 header click

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Box/index.tsx
- react/components/PageBlock/index.js
As the title says... Fixes #1147 
[Running workspace](https://refact--madeirasgasometro.myvtex.com/admin/app/vtexlog/reports/performance?month=1&quarter=false). You can see the boxes have the same height.
> Add 'fit' prop to PageBlock and Box components

- CHANGELOG.md
- react/components/Conditions/index.tsx
- react/components/Statement/Atoms/ObjectAtom.tsx
- react/components/Statement/Atoms/SubjectAtom.tsx
- react/components/Statement/Atoms/VerbAtom.tsx
- react/components/Statement/index.tsx
To enhance Conditions component layout with long object inputs.
In a scenario where the object component is a MultiSelect, for example, it is usually hard to show more then 2 or 3 options without having some scrollbars
or some other small troubles 😝 
As previously discussed in the design meeting, it was agreed that wrap components could be a god solution.
I've also made some margin/padding adjustments to keep consistency.
As described before.
[Running workspace](https://vlauxtst--sandboxintegracao.myvtex.com/admin/promotions/new/)
Select "Price Effect"
Affected Items -> Specific Products
And there you see the conditions component.
Using Styleguidist (docs) example
> Conditions layout

- CHANGELOG.md
- react/components/NumericStepper/index.js
Classes starting with `vtex-` can be freely customized in Store Framework. That's the scape hatch we created since Styleguide doesnt provide native CSS Handles.
NumericStepper classes didn't have the preffix `vtex-`, this commits adds those preffixes.
I decided to add new classes to avoid breaking possible users who are using the current classes.
Be able to customize NumericStepper in Store Framework.
n/a
n/a
> Add missing namespaced CSS classes to NumericStepper

- CHANGELOG.md
- react/components/RadioGroup/index.js
✅ Closes: #1159
add padding on the last item
[Running workspace](http://styleguide.vtex.com/#/Components/Forms/RadioGroup)
> fix: 🐛 padding on the last item

- react/components/Conditions/StrategySelector.tsx
- react/components/Conditions/index.tsx
- react/components/Statement/index.tsx
- react/components/Statement/typings.d.ts
As the title says. #trivial #1083
> [Conditions] Fix lint errors

- CHANGELOG.md
- react/components/Checkbox/index.js
add value to indeterminate attribute
✅ Closes: #1146
add this code on sandbox in the styleguide docs site
```js
class CheckboxWithRef extends React.Component {
constructor() {
super(); 
this.state = { checked: false };
this.reference = React.createRef();
}
render() {
window.REFC = this.reference
return (
<Checkbox
checked={this.state.checked}
partial
id="option-partial"
label="Partial"
ref={this.reference}
name="default-checkbox-group"
onChange={e => this.setState({ checked: !this.state.checked })}
value="option-partial"
/>
)
}
}
;<CheckboxWithRef />
```
You can find element like this:
```js
t = document.querySelector("#option-partial")
t.indeterminate
// true
```
or using ref
```js
window.REFC.current.indeterminate
// true
```
> fix: 🐛 using indeterminate on checkbox when partial true

- CHANGELOG.md
- react/components/AutocompleteInput/README.md
Fix the example in our style guide page
The code snippet showing how to create a custom component to render the autocomplete input options it's passing down a useless prop to the `<button/>` component and showing a warning on browser console when used.
Check [here](https://github.com/vtex/styleguide/tree/1eed4dd68607760c035e7883160e2f722245d0d1/react/components/AutocompleteInput) under the section `Custom option rendering`.
> Fix autocomplete input custom option example

- .eslintrc
- CHANGELOG.md
- react/components/NumericStepper/README.md
- react/components/NumericStepper/index.js
This allow to use the unitMultiplier and measurementUnit fields in the product quantity
I added the following new properties to the Numeric Stepper component:
unitMultiplier: number (e.g: 0.3)
measurementUnit: string (e.g: Kg)
showMeasurementUnit: boolean (e.g: true)
And then, I formatted the displayValue in the input tag
This allow to use the unitMultiplier and measurementUnit fields in the product quantity
[Running workspace](https://multiplier--cbyio.myvtex.com/)
Most markets need this feature to sell in different units
Link this code version and use it in a store that has different multipliers. I maked another pull request in the product-quantity component: https://github.com/vtex-apps/product-quantity/pull/15
Link these two code and manually test
> Feature/ Allow units multiplier in numeric stepper component

- CHANGELOG.md
- react/components/ActionMenu/index.js
- react/components/Menu/index.js
As the title says, these components have fixed default widths and that's not good at all.
When all menu options have smaller widths than the default, the menu is weird.
[Running workspace](https://logistics--ambienteqa.myvtex.com/admin/shipping-strategy/warehouses/)
> Remove ActionMenu and Menu default fixed width

- CHANGELOG.md
- react/components/AutocompleteInput/index.tsx
When one of the autocomplete options is selected, you cannot modify the entry term. This is because the input value varies between the term and the option, depending on the index of the option list, which was not being changed when a modification was made.
To see the problem do [workspace](https://styleguidebefore--cosmetics1.myvtex.com/admin/collections/):
1) Click on the input box;
2) Type something or just select an autocomplete option using the arrowDown or arrowUp keys on 
the keyboard (without pressing enter);
3) Try to delete the input term.
Follow the same steps mentioned before in the [workspace](https://styleguidej--cosmetics1.myvtex.com/admin/collections/)
Before:
After:
> Fix bug when trying to modify the entry when an option is selected in AutocompleteInput

- CHANGELOG.md
- react/components/Tooltip/tooltip.css
As the title says, it's `max-height` should be removed. We had a [discussion](https://vtex.slack.com/archives/C1MCRG7CK/p1588169123243900) about this and it doesn't make sense for the Styleguide to guess what's the ideal tooltip's `max-height`.
Before that, some information could not be shown if the content's height was greater than the `max-height`.
[Running workspace](https://logistics--ambienteqa.myvtex.com/admin/shipping-strategy/loading-docks/)
> Remove tooltip popup max-height

- CHANGELOG.md
- react/components/Tooltip/TooltipPopup.tsx
- react/components/Tooltip/index.tsx
As the title says, add a container prop so the Tooltip be rendered, for example, in the `window.top` document.
It could not be rendered outside the `document.body` (the default container element).
[Running workspace](https://tooltip--ambienteqa.myvtex.com/admin/shipping-strategy/shipping-policies). Click to delete any shipping policy and in the Modal (located in `window.top`) put the cursor in the title (⚠️ please do not delete the policy 😅 ).
> Add container prop to Tooltip component

- CHANGELOG.md
- react/components/RadioGroup/README.md
- react/components/RadioGroup/index.js
Highlight the radio group border according to the state(whether there is an error or not).
[Running workspace](https://seller3--sandboxintegracao.myvtex.com/admin/new-seller/custom/)
The `<RadioGroup>` component does not have props that indicate errors. We are developing a product and when the user does not fill the field(RadioGroup in this case), we need to change the border color to red indicating that an error happened. To solve this problem we will add two props, `error` and `errorMessage` that indicate respectively whether there is an error or not and the error message itself.
1. Go to this [running workspace](https://seller3--sandboxintegracao.myvtex.com/admin/new-seller/custom/)
2. Then press the button `Continue`;
3. Then you should see the error displayed on the field `Type *`.
> Radio group error props

- CHANGELOG.md
- manifest.json
- package.json
- react/EXPERIMENTAL_useTableContext.ts
- react/components/EXPERIMENTAL_Table/Sections/Cell.tsx
- react/components/EXPERIMENTAL_Table/Sections/Row.tsx
- react/components/EXPERIMENTAL_Table/Sections/Thead.tsx
- react/components/EXPERIMENTAL_Table/Sections/index.tsx
- react/components/EXPERIMENTAL_Table/docs/Advanced.md
- react/components/EXPERIMENTAL_Table/docs/Features.md
- react/components/EXPERIMENTAL_Table/hooks/__tests__/useTableMeasures.test.ts
- react/components/EXPERIMENTAL_Table/hooks/__tests__/useTableVisibility.test.ts
- react/components/EXPERIMENTAL_Table/hooks/useTableMeasures.tsx
- react/components/EXPERIMENTAL_Table/hooks/useTableVisibility.ts
➕ `hideColumns` & `showColumns` functions to `useTableVisibility`
➕ `bodyHeight` memo to `useTableMeasures`
➕`disableScroll` to `Table.Sections`
🛠`Table.Body.Cell` unstable heights
These changes make D&D (not Dungeons and Dragons 🐉) possible:
[Running workspace](https://organizerdnd--cosmetics1.myvtex.com/admin/app/collections/4882)
You must clone the repository, install de dependencies, and start the app. Then, navigate to the Table section.
> Small updates to make TableV2 more flexible and reliable on Composable Mode

- CHANGELOG.md
- react/components/Button/index.js
In the workspace we have this modal and every row of the modal is a button that has the styleguide button inside, so what we want when press tab is to just focus the rows, but not the `Add` button
1. [Running workspace](https://linebutton--storecomponents.myvtex.com/admin/app/new-cms/edit/new)
2. Click on the plus button below the page details
3. Use tab to navigate between elements and see that the button `Add` is not focused
> Add 'tabIndex' prop to 'Button'

- CHANGELOG.md
- react/components/MultiSelect/index.js
Add the props `error` and `errorMessage` to `<MultiSelect/>`.
[Running workspace](https://seller3--sandboxintegracao.myvtex.com/admin/new-seller/custom/)
Currently, we are using the old component `Multiselect` since the new one does not meet our requirements (it breaks when being used in a modal outside the iframe). One feature that we need, is the error highlight that it's not implemented yet in our styleguide on the `<Multiselect/>` component.
1. Go to this [Running workspace](https://seller3--sandboxintegracao.myvtex.com/admin/new-seller/custom/)
2. Try to submit the form without filling out any field
3. Then check the error highlight on the input `Trade policies*`
> Multi select error props

- CHANGELOG.md
- react/components/Alert/index.js
- react/components/icon/Close/index.js
This is a non-breaking change to add some accessibility features to the alert.
[Running workspace](https://accessibility--content.myvtex.com/admin/app/new-cms/edit/new)
1- Allow developers to use `focusOnOpen` property to make the cursor focus change to either the action or dismiss buttons
2- Make screen readers announce the alert error as soon as it pops up in the screen
You can go to the workspace link above and try saving a document without filling any information. This will trigger an error. Then you should try repeating the action and, in the second time, dismissing the alert.
You should be able to do all this using just your keyboard.
If you have voice over activated, you should be able to hear the entire experience seamlessly.
> Make alert accessible

- CHANGELOG.md
- react/components/Input/index.js
- react/components/Modal/FocusTrap.tsx
- react/components/Modal/README.md
- react/components/Modal/__snapshots__/index.test.tsx.snap
- react/components/Modal/index.test.tsx
- react/components/Modal/index.tsx
- react/components/Modal/modal.stories.tsx
- react/components/ModalDialog/__snapshots__/index.test.tsx.snap
Implement our own solution to trap focus in Modal.
Dialogs must have focus trapped inside.
`yarn && yarn storybook`
1. Go to http://localhost:6006/?path=/story/components-modal--default
2. Navigate through Modal with `TAB` and `SHIFT+TAB` and check if it is trapped inside modal.
> Add TrapFocus component in Modal and fix Input autoFocus

- react/components/MultiSelect/DropdownList.js
- react/components/NumericStepper/index.js
- react/components/Radio/index.js
- react/components/RadioGroup/index.js
> Fix Multiselect, NumericStepper, Radio & RadioGroup lint issues

- react/components/EXPERIMENTAL_useCheckboxTree/__tests__/util.test.ts
- react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
- react/components/EXPERIMENTAL_useCheckboxTree/reducer.ts
- react/components/EXPERIMENTAL_useCheckboxTree/util.ts
Fix es/ts lint issues by skipping then. This is done because the component needs refactoring before leave experimental. (Huge fixes would be lost)
> #trivial Disable tslint & eslint issues of useCheckboxTree

- CHANGELOG.md
- react/components/NumericStepper/index.js
`NumericStepper` has a weird behavior when there isn't a suffix. This contribution tries to fix it.
I've parsed the suffix variable to check and see if there is any. In which case it puts whitespace between the number and the suffix, otherwise, it adds no space.
You can check the behavior here https://www.als.com/edelws-cord-bulk-per-foot/p
Shoppers that want to put a high quantity in their carts are having trouble.
Just run `yarn styleguide`
> Remove trailing space from numericStepper when suffix doesn't exist

- CHANGELOG.md
- react/components/Textarea/index.js
We need to have the ref of `Textarea` in order to use [react-hook-form-jsonschema](https://github.com/vtex/react-hook-form-jsonschema)
[Running workspace](https://textarea--miriadeit.myvtex.com/contact-us?__bindingAddress=www.miriade.com/it)
[Worksapce with the problem](https://nolink--miriadeit.myvtex.com/contact-us?__bindingAddress=www.miriade.com/it)
> Add forwardedRef to Textarea

- CHANGELOG.md
- react/components/Dropdown/index.js
Fixes #1219. Also this fixes the border color of the dropdown when it is focused to match the same as the input component.
Issue:
With this PR changes:
> Fix dropdown background on error and border color on focus

- CHANGELOG.md
- react/components/AutocompleteInput/SearchInput/index.tsx
Add a disabled background when the `AutocompleteInput` is disabled
Change disabled to `true` in an AutocompleteInput example.
**Before**
**After**
> Fix AutocompleteInput disabled style

- CHANGELOG.md
- react/components/Checkbox/index.js
- react/components/Checkbox/index.test.js
`Checkbox`  wasn't accepting refs that had the type `function` and we need refs that work with functions (like https://github.com/vtex/styleguide/pull/1217)
1. [Running workspace](https://klyngercheckbox--unileverb2b.myvtex.com/)
2. Click on `Registrar`
3. Scroll and click in the checkbox, it should work
> Fix Checkbox forwardedRef not accepting function refs

- CHANGELOG.md
- react/components/FilterBar/FilterTag.js
- react/components/FilterBar/README.md
- react/components/FilterBar/index.js
A missing prop to disable all filters.
On the preview in the link below, check the disabled example.
> Add disabled prop to FilterBar

- react/components/EXPERIMENTAL_Charts/BarChart/index.tsx
- react/components/EXPERIMENTAL_Charts/BubbleChart/index.tsx
- react/components/EXPERIMENTAL_Charts/LineChart/index.tsx
- react/components/EXPERIMENTAL_Charts/ScatterChart/index.tsx
- react/components/EXPERIMENTAL_Charts/helpers.ts
- yarn.lock
> #trivial Disable experimental charts tslint issues

- CHANGELOG.md
- react/components/FilterBar/FilterTag.js
- react/components/FilterBar/README.md
Fix FilterTag disabled style when there is a statement selected.
`IconClose` being active even through the filter tag is disabled
**Before**
**After**
> Fix FilterTag disabled style

- CHANGELOG.md
- react/components/FilterBar/FilterTag.js
As title says.
Filter bar buttons were not rendering Fabriga font.
https://styleguide-git-fix-filter-bar-font.styleguide-core.vercel.app/#/Components/Display/Table
Before:
After:
> Fix filter bar button font

- CHANGELOG.md
- react/components/EXPERIMENTAL_Table/Sections/LoadedView.tsx
- react/components/EXPERIMENTAL_Table/Sections/Tbody.tsx
- react/components/EXPERIMENTAL_Table/Sections/index.tsx
- react/components/EXPERIMENTAL_Table/docs/Advanced.md
Export the feature of hiding the table's body when the table is not loaded or is empty to be used in tables with custom body
If you open [this workspace](https://oldjoserenan--cosmetics1.myvtex.com/admin/app/collections/6268) on firefox and click on "My collection" tab, you will see that the empty state label will be shown at the bottom of the page, if you open it on chrome, it will be in the right position, but if you check on the inspector, will see that the table's tbody is being rendered, that's because we use a custom tbody instead of the styleguide default.
[This workspace](https://joserenan--cosmetics1.myvtex.com/admin/app/collections/6268) uses the component created (`Table.Sections.LoadedView`) wrapping the custom tbody, solving the problem
Empty state …
> Add component to hide loading and empty tables

- CHANGELOG.md
- react/components/EXPERIMENTAL_Table/Sections/Cell.tsx
- react/components/EXPERIMENTAL_Table/Sections/Row.tsx
- react/components/EXPERIMENTAL_Table/docs/Advanced.md
- react/components/Slider/index.js
The devs must be able to use cells easily
No need
> Enable custom style on Cell & content render-prop

- CHANGELOG.md
- react/components/FilterBar/FilterTag.js
- react/components/FilterBar/index.js
- react/components/utils/withDeviceHoc.tsx
Depends on https://github.com/vtex/admin-collections/pull/360
Fix the device detection in the `withDeviceHoc` that it not consistent when the application is SSR.
[Running workspace](https://filtertags--cosmetics1.myvtex.com/admin/app/collections/7031?tab=add)
The `withDeviceHoc` HOC that detects the device is not consistent when the application is SSR, causing re-rendering with the wrong device type as prop. To resolve this, was added a option to pass this check as a prop in the`FilterBar` component.
In the running workspace, switch from tab `Adicionar Produtos` to `Minha Coleção`
You can check an example of usage [here](https://github.com/vtex/admin-collections/blob/ca7ed3dec5bf7a620a9e62b813eb005600d3aeb6/react/components/CollectionView/ProductsContent/ProductsTable/OrganizerTable/compon …
> Fix the device detection in the `withDeviceHoc` that it not consistent when the application is SSR.

- react/components/ButtonPlain/index.tsx
- react/components/Spinner/index.tsx
- react/utilities/mergeRef/index.ts
> #trivial Fix button plain & spinner & mergeRef types

- CHANGELOG.md
- react/components/FilterBar/FilterTag.js
`yarn && yarn styleguide` or check [here](https://styleguide-git-fix-filtertag-icon-disabled-style.styleguide-core.vercel.app/#/Components/Display/FilterBar)
Check the disabled example.
**Before**
**After**
> Fix filterBar clear icon disabled style

- CHANGELOG.md
- react/components/FilterBar/index.js
To update visible filter options when statements change.
We recently changed the `admin-promotions` app to save filters/pagination/search state during navigation (this was an old feature requested by designers and users). It worked smoothly, except for the last filter (trade policies), which is hidden by default (under "more" options). When restoring its state, the filter kept hidden and unavailable, even though the "clear filters" was enabled. This PR aims to fix this issue, considering filter statements changes on the hidden filters evaluation.
Current code: https://abacate--pricingqa.myvtex.com/admin/promotions
Updated code: https://vlauxbeta--pricingqa.myvtex.com/admin/promotions
Add a filter by Trade Policy (TP). Refresh the page. 
Current behaviour: 
- TP filter cannot be restored; …
> Show hidden filters for existing statements

- CHANGELOG.md
- react/components/EXPERIMENTAL_Select/colors.js
- react/components/EXPERIMENTAL_Select/index.js
- react/components/EXPERIMENTAL_Select/styles.js
Add some custom styles to react-select in order to correspond to our design system style.
Since height, padding and font size from select were different from other inputs, they use to get unaligned when together:
Placeholder font size:
[Running workspace](https://vlauxbeta--pricingqa.myvtex.com/admin/promotions/1a18dd71-26ae-428b-a425-af6d816af784/)
> Adjust react-select style

- CHANGELOG.md
- react/components/EXPERIMENTAL_Select/Option.tsx
- react/components/EXPERIMENTAL_Select/colors.js
- react/components/EXPERIMENTAL_Select/index.js
As discussed on the last Styleguide's working session, following the work done on https://github.com/vtex/styleguide/pull/1249, we would like to do some more changes on our select to make it more consistent with our Design System. 
One defined actionable was to change de dropdown behaviour to show the selected option with a checkbox in front instead of highlighting it with a primary color (`react-select`'s default).
Also fixes multi-select's tag hover ;-) 
https://styleguide-git-feature-custom-option-comp.styleguide-core.vercel.app/
Before:
After:
> Add custom option component to react-select

- CHANGELOG.md
- react/components/EXPERIMENTAL_Select/README.md
- react/components/EXPERIMENTAL_Select/index.js
Allows the no select menu to overflow the modal
Currently, when using select within a modal, it ends up having the overflow with error.
entering the documentation and going to the select session, last example
> fix select menu overflow

- CHANGELOG.md
- react/components/Tooltip/TooltipPopup.tsx
Now the idea is to use the `container.clientWidth` prop to calculate collisions alongside with `window.innerWidth`.
Tooltip getting cropped out of the screen
Access, at the Vercel CI link, the tooltip page. At the first example, replace it for this code:
```jsx
const Button = require('../Button').default
;<div className="flex w-100 justify-between">
<Tooltip label="Tooltip text">
<Button variation="tertiary">Top</Button>
</Tooltip>
<Tooltip label="Tooltip text" position="left">
<Button variation="tertiary">Left</Button>
</Tooltip>
<Tooltip label="Tooltip text" position="right">
<Button variation="tertiary">Right</Button>
</Tooltip>
<Tooltip label="Tooltip textTooltip textTooltip textTooltip textTooltip textTooltip textTooltip textTooltip textTooltip text" position="right" trigger="focus"> …
```
> Fix Tooltip position calculation

- react/components/Tooltip/README.md
Fix sample code for using icons with tooltips
Wrong: `<Edit />` and `<Info />`
Correct: `<IconEdit />` and `<IconInfo />`
I was [trying to use the sample code in an app](https://vtex.slack.com/archives/C1MCRG7CK/p1593651613061000) and got an error. This was because the component names for the icons were wrong. Not sure if imports should also be fixed in this sample code or renamed in [this page](https://styleguide.vtex.com/#/Icons), though.
Copy and paste the sample code and try building it in VTEX IO.
> Fixed tooltip icon sample code

- CHANGELOG.md
- react/components/EmptyState/index.js
- react/components/Table/SimpleTable.js
As title says. See discussion [here](https://vtex.slack.com/archives/C1MCRG7CK/p1593715263074400).
Changes made:
- empty state content vertically aligned
- width changed from 50 to 60% on large screens (>64rem)
- emptyStateLabel using h4 instead of h3
https://styleguide-git-fix-table-empty-state.styleguide-core.vercel.app/#/Components/Display/Table
Before:
After:
Before:
After:
> Table's empty state style

- CHANGELOG.md
- react/components/PageHeader/index.js
As title says.
Button link on PageHeader has an exceeding padding on the right.
https://styleguide-git-fix-page-header-btn.styleguide-core.vercel.app/#/Components/Admin%20structure/PageHeader
(using ButtonPlain as recommended by @davicosta99)
> Fix PageHeader link button hover

- CHANGELOG.md
- react/components/ActionMenu/README.md
- react/components/ActionMenu/index.js
- react/components/Menu/index.js
Simple as described on title. Details on linked issue #1150 
https://styleguide-git-fix-1150disabled-menu-options.styleguide-core.vercel.app/#/Components/Forms/ActionMenu
> Add disabled prop to ActionMenu items

- CHANGELOG.md
- react/components/InputSearch/index.js
As title says. Details on linked issue #1254 
Disabled button is visible even when input is disabled. This allow input content to be cleared.
https://styleguide-git-fix-1254hide-clear-when-disabled.styleguide-core.vercel.app/#/Components/Forms/InputSearch
> Hide clear button on `InputSearch` when disabled

- CHANGELOG.md
- react/components/EXPERIMENTAL_Select/index.js
- react/components/EXPERIMENTAL_Select/styles.js
Regular sized select's label size should be `t-small`
Input label sizes:
Select label sizes:
> Fix select label size on regular variation

- CHANGELOG.md
- react/components/EXPERIMENTAL_Select/Control.js
- react/components/EXPERIMENTAL_Select/DropdownIndicator.js
- react/components/EXPERIMENTAL_Select/index.js
As the title says, the current `Select` implementation doesn't allow accents on it but it should.
Basically, if you type anything with an accent in the `Select` input, the value will be computed like this:
Some explanation/context 🤓 
This is happening because of the Select's `componentDidUpdate` method's implementation. To fix a focus bug on PR #524, this method was implemented and did a manual focus on the component.
The problem was happening because some custom components (`Control` and `DropdownIndicator`) were redefined every time the component renders. As **brand new** components (and not the same with other props) were added to the component tree, React didn't preserve their state and the input lost its focus.
Now, with the state preserved, the browser can know that this apostrophe …
> Allow accent on Select's input change

- CHANGELOG.md
- react/components/AutocompleteInput/README.md
- react/components/AutocompleteInput/SearchInput/index.tsx
- react/components/AutocompleteInput/index.tsx
As the title says, the idea is to have an optional search button.
Some cases need an autocomplete to be put in different contexts from search (other design systems do that as well).
Only two examples:
- [Angular Material](https://material.angular.io/components/autocomplete/examples)
- [Ant Design](https://ant.design/components/auto-complete/)
> Change AutocompleteInput search button to be optional

- CHANGELOG.md
- react/components/Conditions/index.tsx
As title says.
Operator (`StrategySelector`) label using wrong font color:
https://styleguide-git-fix-conditions-label-color.styleguide-core.vercel.app/#/Components/Forms/Conditions
Now using `c-on-base`
> Fix conditions' operator label color

- CHANGELOG.md
- react/components/ActionMenu/README.md
- react/components/ActionMenu/index.js
- react/components/Menu/index.js
As the title says, this is meant to better test action menu items.
The `ActionMenu` selectors are so much likely to fail (as the z-index change made the `vtex.admin-logistics` tests fail).
At the last example:
> Add testId property to option in ActionMenu component

- react/components/FilterBar/FilterTag.js
As @kevinch specified in PR #1268, people come and go while teams remain. I removed the targeting for users and includes a nomination for the vtex team.
Removes indication of specific people and includes something more generic.
It can be tested by viewing the FilterBar documentation.
It is not necessary.
> Removes team-specific collaborators #1268

- CHANGELOG.md
- react/components/AutocompleteInput/README.md
- react/components/AutocompleteInput/index.tsx
As the title says, this prop should be added.
Today it's not possible to give some feedback to the users about something related to the `AutocompleteInput` options. For example, if the suggestions (loaded from the server) cannot be queried, this error can now be shown by using the `options.customMessage` prop.
There are plenty more examples of usages (error/warning messages, hints about the field, etc) and that's why the prop name is generic.
> Add options.customMessage prop to AutocompleteInput

- CHANGELOG.md
- react/components/AutocompleteInput/README.md
- react/components/AutocompleteInput/SearchInput/index.tsx
- react/components/AutocompleteInput/__snapshots__/index.test.tsx.snap
- react/components/AutocompleteInput/index.tsx
There was no error state on `AutocompleteInput` component. [Discussion on Slack](https://vtex.slack.com/archives/C1MCRG7CK/p1595862494183500)
> Add input.error and input.errorMessage props to AutocompleteInput

- CHANGELOG.md
- react/components/AutocompleteInput/README.md
- react/components/AutocompleteInput/index.tsx
The problem is that the `onChange` function from the `HTMLInput` is being overwritten and the current props definition doesn't express that. So, when passing the right `onChange` function, the component's types break.
> Fix AutocompleteInput typing definitions

- CHANGELOG.md
- manifest.json
- package.json
- `options.customMessage` prop to `AutocompleteInput`.
- `error` and `errorMessage` props to `AutocompleteInput` component.
- Tooltip `Portal` proptypes.
- `AutocompleteInput` typing definitions.
> Release v9.126.0

- CHANGELOG.md
- react/components/Dropzone/README.md
- react/components/Dropzone/index.js
Expose more properties of the `react-dropzone` lib through Styleguide's `<Dropzone />` component. This should give the community (and me =P) more flexibility when using the component.
None. It's a feature.
We're developing an admin app that only takes .xml files as the input of some of its fields. Being able to specify maximum file size and extension is extremely helpful for out app.
Clone the project and run `yarn install && yarn start`. This will launch the Styleguide page and then you can see the doc for the component as well as a working example on http://127.0.0.1:6061/#/Components/Forms/Dropzone.
> Exposes more props of the Dropzone component

- CHANGELOG.md
- react/components/AutocompleteInput/SearchInput/index.tsx
- react/components/AutocompleteInput/__snapshots__/index.test.tsx.snap
Fix #1306 
Creates a new condition to adjust the padding-right when CloseIconInput does not show. 
[Running workspace](https://fixautocomplete--cosmetics1.myvtex.com/admin/app/collections/9259?tab=add)
#1306 
1- Try to put a long placehold in AutoCompleteInput 
2- Check if the padding is changing when the CloseIconInput isn't being shown.
Before
After
> Fix padding right to AutoComplete

- CHANGELOG.md
- react/components/ActionMenu/index.js
Add onClick prop to ActionMenu to provide event handling.
Example:
Go into [this workspace](https://actionmenu--recorrenciaqa.myvtex.com/admin/app/orders/1052461639489-01) mobile version and try to click on the action menu like the gif below. The collapsible will also move when the button is clicked, which is not wanted. With the onClick prop, I'm able to stop event propagation.
Note: The collapsible being used in this example is a copy of the Styleguide's but with some small design changes like margins and the caret to fit the Admin V4 aesthetic.
https://fixed--recorrenciaqa.myvtex.com/admin/app/orders/1052461639489-01
Before:
After:
> Add onClick prop to ActionMenu

- CHANGELOG.md
- react/components/Checkbox/index.js
- react/components/Checkbox/styles.css
Fixes #1299 
When the Checkbox has a text that breaks the line it overflows over the box, the problem is caused due to not having `min-width` property.
Have a checkbox with a text that cannot be displayed in a single line.
Before:
> Fix Checkbox alignment with large texts

- .babelrc
- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .storybook/main.ts
- .storybook/manager.ts
- .storybook/preview.tsx
- README.md
- babel.config.js
- config/webpack.config.js
- package.json
- react/components/Button/button.stories.tsx
- react/components/Tooltip/index.tsx
- react/components/Tooltip/tooltip.stories.tsx
- react/playground/All.tsx
- react/playground/ExamplePage.tsx
- react/playground/Playground.tsx
- react/playground/stories.tsx
- yarn.lock
This is a [previously work done](https://github.com/vtex/styleguide/pull/1158) to the branch `features`, but since this branch has been discontinued I'm moving to the `master`.
We need an environment with hot-loading and isolated components builds to help us develop our components.
`yarn && yarn storybook`
Visit http://localhost:6006/
> #trivial Add storybook to the master branch

- CHANGELOG.md
- react/components/ColorPicker/HexInput.js
- react/components/ColorPicker/colorUtil.js
To fix an issue on regex validation for hexadecimal colors
Colors with only three chars are being returned false (e.g. #FFF), which then causes an error on the next line: 
```
else if ('h' in color && 's' in color && 'v' in color) return COLOR_FORMAT.HSV
```
```
Uncaught TypeError: Cannot use 'in' operator to search for 'h' in #FFF
```
You can use the ColorPicker and on the `color` prop use a three chars hexa color: 
https://github.com/vtex-apps/admin-pages/blob/22593b3f44aab7add43e96b7771e1c6788b79987/react/components/admin/store/PWAForm/index.tsx#L188
> Fixed hexadecimal regex validation

- CHANGELOG.md
- react/components/InputSearch/index.js
Fixes ##1302.
keeps the search Icon vertically aligned, as it should be
open the InputSearch component and see if the icons are centered horizontally and vertically
before:
after:
- [] New feature (a nonstop change that adds functionality)
- [] Breaking the change (fix or feature that would cause the existing functionality to be changed)
- [] Requires changes to the documentation, which has been updated accordingly.
> fix: InputSearch icon unaligned

- CHANGELOG.md
- react/components/AutocompleteInput/index.tsx
- yarn.lock
When the search is made by clicking on the search button the popup doesn't close.
https://styleguide-git-fix-autocompleteinput-popup-not-closing.styleguide-core.vercel.app/#/Components/Forms/AutocompleteInput
1. Type something in the `AutocompleteInput`
2. Click on the search button
3. Check if the popup closes.
> Fix AutocompleteInput popup not closing when clicking on search button

- CHANGELOG.md
- react/components/EXPERIMENTAL_Table/Sections/Cell.tsx
As the title says, the cell's suffix display was broken.
With `absolute` class, the cell's suffix width was not being considered and it was breaking the table's layout.
> Fix Table v2 cell suffix display

- CHANGELOG.md
- manifest.json
- package.json
- `AutocompleteInput` popup not closing when clicking on search button.
- **EXPERIMENTAL_Table** cell suffix classes.
> Release v9.129.1

- CHANGELOG.md
- react/components/AutocompleteInput/README.md
- react/components/AutocompleteInput/SearchInput/index.tsx
- react/components/AutocompleteInput/__snapshots__/index.test.tsx.snap
- react/components/AutocompleteInput/index.tsx
Also, fixes the "Without search button" logic.
There was no way of defining prefix or suffix on `AutocompleteInput`. And about the search button, `handleSearch` was always being passed to `SearchInput`.
> Add input.prefix and input.suffix to AutocompleteInput

- CHANGELOG.md
- manifest.json
- package.json
- **AutocompleteInput** `input.prefix` and `input.suffix` props.
- **AutocompleteInput** without search button logic.
> Release v9.130.0

- CHANGELOG.md
- react/components/AutocompleteInput/index.tsx
As the title says, the `term` value (private state) should follow `input.value` changes to allow control outside the component.
Basically, without it, the parent component changes on `input.value` will not reflect on `AutocompleteInput`. The `term` variable should only be used to control the input value when browsing options with the arrow keys.
1. Access this [workspace](https://logistics--logisticsqa.myvtex.com/admin/inventory)
2. Change any item's quantity **but don't save it**
3. Change the autocomplete input value. E.g.: Type 'chaveiro'.
4. Select an option.
5. When the modal shows up, click "Keep editing".
6. The input value should be cleared.
> Fix AutocompleteInput term to follow input.value changes

- CHANGELOG.md
- react/components/AutocompleteInput/Option.tsx
- react/components/AutocompleteInput/hooks.ts
- react/components/AutocompleteInput/index.tsx
Fix the double focus issue when navigating through the suggested options with `tab` and `arrowKeyDown`.  Also now it's possible to start over from the beginning of the suggested options when reaching the end of the list with `arrowKeyDown`
When navigating through the suggested options with `tab` and the `arrowKeyDown`, two options would be marked out with grey as shown below:
1. Go to [this workspace](https://tabnavigation--vtexhelp.myvtex.com/?__bindingAddress=vtexhelp.myvtex.com/)
2. Search for something (eg: Amazon)
3. If `tab` is pressed, the popover should be hidden
4. Arrow keys navigation should behave normally
> Fix AutocompleteInput 'double focus' when navigating with tab + arrow keys

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/context/loading.tsx
- react/components/EXPERIMENTAL_Table/index.tsx
Publishing Styleguide v9.132.0 on VTEX IO failed because of these types definitions.
Just try to `vtex link` this branch on any workspace
> Fix EXPERIMENTAL_Table emptyState type definitions

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Dropdown/index.js
- react/components/Input/index.js
- react/components/Textarea/index.js
Fixes https://github.com/vtex-apps/store-components/issues/871
Make it possible to customize the error and help text elements in Store Framework.
https://highlight--storecomponents.myvtex.com/
1. Open the workspace
2. Go to the bottom of the page
3. Click on the Submit of the Newsletter
4. Check the error message element classes
> Add CSS handles to Input, Dropdown, and Textarea error messages and help texts

- CHANGELOG.md
- react/components/Slider/index.js
Fix a race condition in the Slider component
When the Slider is rendered, the component will calculate left and right selector positions. This creates. a race condition, and sometimes, only one selector will have the correct position
To reproduce, go to this  [URL](https://storecomponents.myvtex.com/apparel---accessories/accessories/?fuzzy=auto&operator=or&priceRange=994%20TO%202200).
This URL has the query string `priceRange=994%20TO%202200)`, it means that the slider should render the range from 994 to 2200. Like this:
But it is rendering this:
[workspace with the fix](https://sliderracecondition--storecomponents.myvtex.com/apparel---accessories/accessories/?fuzzy=auto&operator=or&priceRange=994%20TO%202200)
> fix slider race condition

- CHANGELOG.md
- react/components/EXPERIMENTAL_Table/Sections/index.tsx
- react/components/EmptyState/index.js
As title says.
Empty state on TableV2 was not taking into account header's height, although Loading state was.
This change does the same as done on the Loading one.
https://styleguide-git-fix-empty-state-height.styleguide-core.vercel.app/#/Components/%F0%9F%91%BB%20Experimental/Table%20V2
Before:
After:
> Fix Table V2 empty state height

- CHANGELOG.md
- manifest.json
- package.json
- **EXPERIMENTAL_Modal** `ref` not properly passed to modal element.
- **EXPERIMENTAL_Table** `emptyState` height
> Release v9.133.2

- CHANGELOG.md
- react/components/EXPERIMENTAL_Modal/FocusTrap.tsx
- react/components/EXPERIMENTAL_Modal/index.tsx
- react/components/EXPERIMENTAL_Modal/modal.css
- react/utilities/useMergeRefs/index.ts
In small screens the modal was exceeding the screen height. 
1. Access Modal v2 on docs
2. Decrease screen height and check if the modal exceeds the screen
**Before**
**After**
> Fix Modal v2 height on small screens

- CHANGELOG.md
- react/components/EXPERIMENTAL_Modal/__snapshots__/index.test.tsx.snap
- react/components/EXPERIMENTAL_Modal/index.tsx
For some reason, if you have content inside the `EXPERIMENTAL_Modal` that exceed the max height (which is supposed to be fine because we have an `overflow-auto` class), on mobile Safari that content is not properly laid out and it can overlap with each other (see the screenshot below). I've found [this StackOverflow](https://stackoverflow.com/questions/42292912/flexbox-max-height-in-ie-and-safari) question that describes this exact same problem, and the only answer posted resolved this issue.
[Running workspace](https://billing--checkoutio.myvtex.com/cart/add?sku=289).
You can see the modal in the payment step of the Checkout, if you select a credit card and click the "ver opções de parcelamento" button, the modal should appear.
But you must test this using either an iPhone, or using the …
> Fix overflown modal content overlapping on mobile Safari

- .gitignore
- CHANGELOG.md
- package.json
The npm package is giving error when using the utilities `useMergeRefs` and `useDisclousure` because they are not included in the compiled package.
1. `yarn build`
2. `yarn link`
3. Run `yarn link "@vtex/styleguide" ` in a project which uses styleguide through `npm`
> Fixed utilities not being compiled on package build

- CHANGELOG.md
- react/components/Tag/index.js
Add a css handle on `Tag` component to be able styling from store-theme.
Adding this class we will be able to style Tag component through VTEX store-theme using css selectors.
[Running workspace](https://minicartcoupon--outletespacohering.myvtex.com/)
Add a product your cart, open minicart and add a coupon. After that you will see a Tag component used by [Coupon](https://github.com/vtex-apps/checkout-coupon) styled.
Example: https://prnt.sc/vm5ipo
> added new css handle for tag component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Dropdown/index.js
- react/components/Input/index.js
This PR fixes a minor inconsistency between the Input and Dropdown components.  Thanks to @davicosta99 for noticing this one.
The Input and Dropdown components both had 14px font-size when their size was set to small. This caused the mobile safari app to zoom in when interacting with them. This PR sets the font-size of these components to 16px no matter their size, fixing the unwanted behavior described previously.
Open this workspace using the mobile safari app and click on the dropdown/input. It shouldn't zoom in.
[Workspace](https://icaroquantity--storecomponents.myvtex.com/fashion-eyeglasses/p)
Before and after the fix:
> Fixing font size of Input and Dropdown with small size

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
- react/components/Button/index.test.tsx
When you pass `isLoading` to the button it disables the button visually but doesn't pass the disabled to the element
[Running workspace](https://styleguidebutton--storecomponents.myvtex.com/admin/app/new-cms/store/notFound/edit/661814e5-42d9-412c-ae54-e5b979b128cb)
1. The button in the right top corner should be loading and the element should have a `disabled` property defined
<details>
```jsx
import Button from '../Button'
<Button isLoading>
A loading disabled button
</Button>
)
export default Playground
```
</details>
> Fix loading button not passing disabled to the button element

- CHANGELOG.md
- react/components/EXPERIMENTAL_Table/Sections/index.tsx
(Resolves #1361)
With custom sections, it is possible to build lines with *dynamic height* . So, setting the table height without scrolling can hide the rendering of some items.
[Running workspace](https://mateusv2--sandboxintegracao.myvtex.com/admin/inventory/)
[![Inventory](https://i.gyazo.com/4aa658bbbb05ec79419c84fb2c54e66b.png)](https://gyazo.com/4aa658bbbb05ec79419c84fb2c54e66b)
> Render the complete table when scrolling is disabled

- CHANGELOG.md
- manifest.json
- package.json
- react/components/InputCurrency/index.js
The global `event` is deprecated. Browsers deal with this object differently and sometimes, it can be unavailable. This PR deal with cases where the `event` is undefined
Go to the workspace, click on "Brake Mounts" and then on "No mount". The `InputCurrency` in the "Price Ranges" will throw an error
[Broken workspace](https://hiago--eriksbikeshop.myvtex.com/cycling)
[Fixed workspace](https://hiago2--eriksbikeshop.myvtex.com/cycling)
> deal with undefined event on InputCurrency

- react/components/Modal/index.js
- react/modules/scrollPollyfill.js
Currently, there is a bug when you click outside of a modal, it will break the whole `my-account` component because of a library (no-scroll) that calls the `window.scroll` function. The error is that `window.scroll is not a function` and instead it's an object
[Workspace with the bug fix](https://wishlistvtex--bestride.myvtex.com/account?__bindingAddress=www.bestride.ro/#/profile)
Environments:
https://www.supermercato.ro/
https://bestride.myvtex.com/
Steps to reproduce:
Login as a customer
Go in "My Account" section
Click on "Logout"
A confirmation modal is opened. Close this modal (Cancel or X)
Actual result:
The elements from the main container disappears and the customer has to refresh the page in order to see again the my account sections
Expected result:
User should remain in the …
> Scroll polyfill

- CHANGELOG.md
- manifest.json
- package.json
- react/components/NumericStepper/index.js
This PR fixes an issue where the `displayValue` of the `NumericStepper` was considering wrong boundaries (min and max values) when using a `unitMultiplier` different from 1.
[Breaking workspace](https://poccarrefourarg.myvtex.com/papa-x-kg-/p)
[Fixed workspace](https://icarovtex--poccarrefourarg.myvtex.com/papa-x-kg-/p)
[Fixed workspace 2](https://icarostepper--storecomponents.myvtex.com/traveler-backpack/p)
Try setting a small value for min and max values and a unitMultiplier different from 1. It increases the real integer `value`, but the `displayValue` remains unchanged when the real integer `value >= maxValue * unitMultiplier`.
> Fixing stepper's displayValue boundary detection

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Charts/LineChart/README.md
Allow the user to set the container's height property.
The `aspect` property in the default config will always overwrite the specified height property. Now we first analyze the user config and check if there's a height property set, and If not, then we set the default `aspect` property.
[Running workspace](https://sortbynotification--vtexlogcarriers.myvtex.com/admin/vtexlog/reports/performance/)
Ignoring the height property:
With the fix:
> Fix getChartDefaultProps ignoring the user's chosen height property

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/Sections/Tbody.tsx
- react/components/EXPERIMENTAL_Table/context/body.tsx
- react/components/EXPERIMENTAL_Table/context/data.tsx
- react/components/EXPERIMENTAL_Table/context/head.tsx
- react/components/EXPERIMENTAL_Table/context/loading.tsx
- react/components/EXPERIMENTAL_Table/context/testing.tsx
- react/components/EXPERIMENTAL_Table/hooks/useTableMeasures.tsx
- react/components/EXPERIMENTAL_Table/hooks/useTableProportion.ts
The table was re-rendering all rows when anything changed inside the Table's children. Because of that, when the table had a lot of items (in the example it has 100 items), it started to make typing slow
[Workspace with the changes](https://tableperformance--storecomponents.myvtex.com/admin/app/new-cms/store)
[Workspace without the changes](https://tableslow--storecomponents.myvtex.com/admin/app/new-cms/store)
1. Open the React Profiler
2. Start recording
3. Type something in the search
4. Stop recording
5. Compare both worksapces
<details>
```jsx
<Layout fullWidth …
```
> Stop re-rendering all rows if the children of the table changes

- CHANGELOG.md
- manifest.json
- package.json
- react/package.json
#trivial like the title says
Explained here: https://vtex.slack.com/archives/C1MCRG7CK/p1618931965010400
"
Hi all! :worry-wave:
Styleguide is using date-fns dependency, but it seems it wasn't explicit included in the package.json because react-datepicker already includes it.
The problem with that is that if you have other dependencies other than styleguide that also depends on date-fns, than the styleguide package might not be using the one that it though it would (since it is asking for the one on the root of the node_modules, instead of being an dependency) and that can cause build problems (my case with the latest version of Cypress + latest version of Styleguide)
I made the dependency on date-fns explicit on this PR
This doesn't change any code or yarn.lock, just the package.json for …
> Make date-fns dependency explicit

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Modal/README.md
- react/components/EXPERIMENTAL_Modal/index.tsx
- react/components/EXPERIMENTAL_Modal/modal.css
- react/components/EXPERIMENTAL_Modal/modal.stories.tsx
Also, it doesn't affect the `responsiveFullScreen` feature.
I need the modal to adjust its size based on the content and also to be able to horizontally fit the screen in some other cases.
You can check out Vercel's deployment of this branch :)
> Add 'fit-horizontally' and 'auto' sizes to EXPERIMENTAL_Modal component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Modal/modal.css
This one:
You can test it in the Vercel build or in [this workspace](https://inventory--qastore.myvtex.com/admin/inventory/?details=reservedQuantity&keyword=&minReservedQuantity=1&page=1&perPage=10&sku=401&warehouseId=1ccaeb6)
> Fix EXPERIMENTAL_Modal 'auto' size max width to avoid overflowing the screen

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/Toolbar/InputSearch.tsx
**EXPERIMENTAL_TableV2** search button click does not work if the onSubmit prop is not passed. 
Solution: Pass onSubmit prop from `InputSearch Wrapper` to `InputSearch` in order to fix search button click. This problem is happing because the `InputSearch` component is using onSubmit `prop` in this [line](https://github.com/vtex/styleguide/blob/master/react/components/InputSearch/index.js#L98).   
[Running workspace](https://storecomponents.myvtex.com/admin/new-cms/faststore/)
The problem happens in the styleguide [example](https://styleguide.vtex.com/#/Components/%F0%9F%91%BB%20Experimental/Table%20V2?id=section-components-1) too
I just linked these changes in the `pedrocms` workspace. You can test it [here](https://pedrocms--storecomponents.myvtex.com/admin/new-cms/faststore/). 
I linked …
> **EXPERIMENTAL_TableV2** search button click does not work if the onSubmit prop is not passed

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
- react/components/NumericStepper/index.js
when clicking on the add to cart or numeric stepper buttons on the mobile autocomplete, the autocomplete closes.
so the user is unable to include more items directly in the autocomplete
[Running workspace](https://thalyta--gigadigital.myvtex.com/)
- in the autocomplete, type a term and click the add to cart button of the suggested product or try to increase the quantity
- the autocomplete should not close
<details>
```jsx
<Layout fullWidth pageHeader={<PageHeader title="Playground" />}>
{/* Add your code here, don't forget to delete after */}
</Layout>
)
export default Playground
``` …
> Fix NumericStepper and Button behavior on touch

- CHANGELOG.md
- manifest.json
- package.json
- react/components/NumericStepper/index.js
Fixes the error generated by the [last release](https://github.com/vtex/styleguide/pull/1381) :sadge:
[With error](https://thalyta1--gigadigital.myvtex.com/) - the error in this workspace is in the `AddToCartButton` which is linked with a similar logic, as I was not able to replicate the error locally for the `NumericStepper`
[Running workspace](https://thalyta--gigadigital.myvtex.com/)
<details>
```jsx
<Layout fullWidth pageHeader={<PageHeader title="Playground" />}>
{/* Add your code here, don't forget to delete after */}
</Layout>
)
export default Playground
```
</details>
> Fix error with undefined navigator

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
We have a bug in the add to cart where the button performs click behavior when scrolling over it on mobile. This is because we use the `onTouchEnd` function (yes, we need this 🥺). 
To fix it, we need to check whether or not a scroll was made on the screen and then decide if there should be a click behavior or not. For this, we need the functions of `onTouchStart` and `onTouchMove`: https://github.com/vtex-apps/add-to-cart-button/pull/78
[Running workspace](https://thalyta--gigadigital.myvtex.com/refrigerante-coca-cola-pet-1l/p)
<details>
```jsx
<Layout fullWidth pageHeader={<PageHeader …
```
> Add onTouchStart and onTouchMove to Button

- CHANGELOG.md
- react/components/Modal/index.js
- react/modules/scrollPollyfill.js
This is related to the fix done here https://github.com/vtex/styleguide/pull/1371 - if you're installing the current version of the app on a workspace where Modal is used, on hard refresh (CTRL + Shift + R) the window.scroll stays undefined during componentDidUpdate.  For some reason the file is not imported properly on hard refresh, after moving the function to Modal/index.js and calling it right before the logic in ComponentDidUpdate the problem was fixed
Can't provide a workspace link because the functionality requires for you to have an account and some dummy data inserted in master data for your email in order for the contracts to show up in your account, but here's a video that describes the issue and shows the fix.
https://user-images.githubusercontent.com/71461884/120172465-c165438 …
> Fixing window scroll not defined

- CHANGELOG.md
- react/components/Dropdown/index.js
Adds the disabled attribute to an option in the dropdown to allow the developer to show disabled items as well
The problem it's solving and the motivation behind this PR are detailed here: https://github.com/vtex-apps/store-components/pull/953
See the testing steps here: https://github.com/vtex-apps/store-components/pull/953 - it depends on the whether or not the options parameter contains the "disabled" key, if it doesn't, it defaults to "false" and has no impact on the functionality.  It will only affect stores that specifically provide that key
Uploading disable_select_options.mp4…
> Adding disabled attr to dropdown select options

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Dropdown/index.js
- **Modal** sometimes not loading `window.scroll` polyfill after the browser hard refresh.
- **Dropdown** `disabled` prop added to options
> Release v9.143.0

- CHANGELOG.md
- react/components/Table/README.md
- react/components/Table/index.js
Possibility to get callback on toggle fields visibility with `onToggleColumn`, `onHideAllColumns` and `onShowAllColumns`
The callback functions `onHideAllColumns` and `onShowAllColumns` returns a string array with active columns, and `onToggleColumn` returns the field changed and a string array with active columns.
I needed to create a feature that save on localstorage a custom visibility created by user, but the controls handlers are not exposed to get a callback when the user did the visibility action.
Because of this I added 3 functions to get this actions and a callback with active fields, to solve my problem and for everyone who wants to use this callback to do something.
```jsx
toolbar={{
...
fields: {
...
onToggleColumn: (params) => {
console.log(params.toggledField) …
```
> Add handle callback on toggle fields visibility

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Dropdown/README.md
- react/components/Dropdown/index.js
- styleguide.config.js
As the title says, these events were missing.
No way for listening to these events on the Dropdown component.
They can be viewed by playing with the first Dropdown examples, which logs on the console when they're fired.
> Add onFocus, onBlur, onMouseEnter and onMouseLeave events to Dropdown

- CHANGELOG.md
- manifest.json
- package.json
ℹ️  Related to #1417 and #1418 
- **Dropdown** `onOpen` and `onClose` unused props.
> Release v9.146.1

- CHANGELOG.md
- manifest.json
- package.json
- react/components/NumericStepper/index.js
This PR aims to solve  [this Known Issue (KI)](https://vtex-dev.atlassian.net/browse/SF-35):
[KI] Product Quantity Selector Error for high-resolution screens.
Copied from Jira Issue:
When rendering high resolutions, the quantity selector doesn't work.
Simulation
- Access the `storecomponents`;
- Open the Chrome inspector
- Set the screen size on 4000px X 2000px with the chrome's DevTools utility
- Refresh the page;
- Wait for the page to be loaded;
- Close the inspector  WITHOUT REFRESHING THE PAGE;
- Try to use the qty selector.
---
While investigating this issue, we noticed that this problem is not related to the high-resolution screens, but to the toggle device toolbar feature of devtools that simulates some touch devices.
As we also have a [previous fix …
> Fix: `NumericStepper` click event

- CHANGELOG.md
- react/components/NumericStepper/index.js
Add a preventDefault numeric steppericStepper to avoid other events triggered
When interacting with the numeric stepper inside a shelf, we are being redirected to a product page
https://tiendaio--tiendamarco.myvtex.com/
Increase and decrease the product quantity
Unlink this version and check again
> fix: NumericStepper redirecting to product page when inside a shelf

- CHANGELOG.md
- manifest.json
- package.json
- Prevents `Slider` range from resetting when the min/max value changes.
> Release v9.146.4

- CHANGELOG.md
- react/components/EXPERIMENTAL_Conditions/Atoms/SubjectAtom.js
- react/components/EXPERIMENTAL_Conditions/Statement.js
- react/components/EXPERIMENTAL_Conditions/index.js
With this we are able to pass a custom message to Subject, Verb and Object when they are empty
Currently we cannot set a custom message when they are empty, blocking the translations of this
* Switch to this branch and run
* Pass a custom message to `noOptionsMessage` in `Conditions` component and see the changes
> Feat/ add noOptionsMessage to Conditions and pass to Select

- CHANGELOG.md
- react/components/AutocompleteInput/README.md
- react/components/AutocompleteInput/__snapshots__/index.test.tsx.snap
- react/components/AutocompleteInput/autocomplete.css
- react/components/AutocompleteInput/index.test.tsx
- react/components/AutocompleteInput/index.tsx
Add a maxHeight property con Autocompleteinput
> Feat: Add scroll on autocomplete
