- src/components/Input/README.md
- src/components/Loader/README.md
- src/components/Loader/index.js
Adding a simple loader. No props. No width. One color.
> Add simple loader

- src/components/Spinner/README.md
- src/components/Spinner/index.js
> Update loader to spinner

- package-lock.json
- package.json
- src/components/Spinner/README.md
- src/components/Spinner/index.css
- src/components/Spinner/index.js
Spinner gained css animation and Styleguide now copies css files to lib folder.
> Update spinner and add copy css files

- package-lock.json
- src/components/Button/README.md
- src/components/Button/index.js
- src/components/Spinner/index.js
- yarn.lock
> Add spinner within button

- package.json
- src/components/Button/index.js
- yarn.lock
This pull request changes the default fontsize to 16px and fixes the default button background color. 
It also improves the hover status of the default button and removes unnecessary white border.
PS: This fix needs an update on VTEX Tachyons regardless the "bg-transparent" class. Waiting for @klzns to do it's magic.
> Improve button layout and fix default button with background transparency

- src/components/Button/README.md
- src/components/Button/index.js
> Improve Button API

- CHANGELOG.md
- package.json
Messed up and merged with master before releasing. This PR just fixes the version and the changelog.
> Release rc39

- package.json
- src/components/Dropdown/index.js
A warning was appearing on VTEX's `render` regarding the prefix
> Fix vendor prefix on dropdown

- src/components/Button/README.md
- src/components/Dropdown/index.js
> Update Button with icon hover state

- CHANGELOG.md
- package.json
- src/components/Radio/README.md
- src/components/Radio/index.js
- src/components/Toggle/README.md
Updated radio's `checked` behavior. Now it's a true boolean expression.
**Before**:
```
<Radio
checked={this.state.checkedRadioValue}
id="radio-0" value="option-0"
... />
<Radio
checked={this.state.checkedRadioValue}
id="radio-1" value="option-1"
... />
<Radio
checked={this.state.checkedRadioValue}
id="radio-2" value="option-2"
... />
```
**After**:
```
<Radio
checked={this.state.checkedRadioValue === 'option-0'}
id="radio-0" value="option-0"
... /> 
<Radio
checked={this.state.checkedRadioValue === 'option-1'}
id="radio-1" value="option-1"
... />
<Radio
checked={this.state.checkedRadioValue === 'option-2'}
id="radio-2" value="option-2"
... />
```
> Update radio prop checked

- CHANGELOG.md
- package.json
- src/components/Input/index.js
Set the `label` that acts as a container to 100% width so that the parent sets the width.
Before:
After:
> Update label width

- src/components/icon/README.md
- styleguide.config.js
O layout não ta dos melhores. Aberto a contribuições.
> Create section to display icons

- CHANGELOG.md
- src/components/Dropdown/index.js
- src/components/Input/index.js
- Change `Input` `required` propType to `bool`;
- Add `number` to `Dropdown` `value` propTypes.
`Dropdown`:
<hr />
`Input`:
> Fix - PropTypes

- CHANGELOG.md
- src/components/Toggle/README.md
- src/components/Toggle/index.js
- src/components/icon/Check/index.js
- src/components/icon/Deny/index.js
> Feature - Toggle size

- CHANGELOG.md
- react/components/Radio/index.js
Title is self explanatory
Example: (it's smoother in "real life")
> Add lil animation to radio

- CHANGELOG.md
- react/components/Toggle/index.js
As we talked on the design meeting, the width of the toggle is twice the width of the circle thing.
Also adjust its animation a little bit.
Before
After
> Decrease the width of the toggle component

- CHANGELOG.md
- react/components/Radio/index.js
> Add blue border to checked radio buttons

- CHANGELOG.md
- react/components/Checkbox/index.js
> Add checkbox animation

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Alert/index.js
> Wrap alert icon in a div

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Toggle/README.md
- react/components/Toggle/index.js
Optional help text can now be added to Toggle as well.
> Add help text option to Toggle

- CHANGELOG.md
- package.json
- react/components/Modal/index.js
Update modal's z-index to step above the topbar in admin.
> Update modal's z-index

- CHANGELOG.md
The `releasy@1.10.0` will bump `CHANGELOG.md` file if has the section `## [Unreleased]`
Now, you guys only need to add the changes on the Unreleased section. When you launch a new version the releasy will bump `manifest.json`, `package.json` and `CHANGELOG.md`. e.g.: 
`releasy --stable --npm --notes`
> Add ## [Unreleased] on changelog

- analytics.js
- styleguide.config.js
Implements https://github.com/vtex/styleguide/issues/208
> Add Google Analytics tracking code

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Radio/index.js
> Fix size of Radio component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Dropdown/index.js
@analuizamtg has raised an issue regarding the dropdown, which was selecting the first item in case the value was null/undefined. This fixes the issue, and adds a warning in case the placeholder is created without values.
> Fix dropdown null value issue

- react/components/EmptyState/README.md
closes https://github.com/vtex/styleguide/issues/137
> Update empty state description

- CHANGELOG.md
- react/components/Input/README.md
- react/components/Input/index.js
- Add `SuffixIcon` to `Input` component
[workspace](https://claudivan--storecomponents.myvtex.com/)
> Add suffix icon

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Input/index.js
> Decrease default Input label's font size

- CHANGELOG.md
- react/components/icon/ArrowBack/index.js
- react/components/icon/ArrowDown/index.js
- react/components/icon/ArrowUp/index.js
- react/components/icon/CaretDown/index.js
- react/components/icon/CaretLeft/index.js
- react/components/icon/CaretRight/index.js
- react/components/icon/CaretUp/index.js
- react/components/icon/Check/index.js
- react/components/icon/Clock/index.js
- react/components/icon/Close/index.js
- react/components/icon/Cog/index.js
- react/components/icon/Copy/index.js
- react/components/icon/Delete/index.js
- react/components/icon/Deny/index.js
- react/components/icon/Download/index.js
- react/components/icon/Edit/index.js
- react/components/icon/ExternalLink/index.js
- react/components/icon/ExternalLinkMini/index.js
- react/components/icon/Failure/index.js
- react/components/icon/Filter/index.js
- react/components/icon/Help/index.js
- react/components/icon/Link/index.js
- react/components/icon/Plus/index.js
- react/components/icon/Save/index.js
- react/components/icon/Search/index.js
- react/components/icon/Success/index.js
- react/components/icon/Upload/index.js
- react/components/icon/Warning/index.js
- react/components/icon/utils.js
> Add CSS hook classes to icons

- package-lock.json
- package.json
And change some packages with vulnerabilities that were fixed automatically by npm.
> Change to vtex-tachyons with color tokens

- react/components/Card/index.js
bg-white -> bg-base
Simples as that
> Change background class to semantic on Card

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Input/index.js
- react/components/Spinner/index.js
> Add new props to input

- CHANGELOG.md
- package.json
- styleguide.config.js
> Style fix on Doc's import instructions

- CHANGELOG.md
- react/components/Spinner/index.js
Fix spinner props
Fix usability of Spinner
> Fix spinner props

- react/components/NumericStepper/index.js
> Fix numeric stepper buttons alignment

- CHANGELOG.md
- react/components/Dropdown/index.js
Forward ref so user can use ref in select.
> Forward Dropdown ref

- .eslintrc
- CHANGELOG.md
- react/components/Button/index.js
Button still clickable while loading is true
Now the user should wait for the loading be false to click on the button and trigger the action again.
[workspace](https://felipe--storecomponents.myvtex.com/)
> Button component should be disabled while loading is true

- CHANGELOG.md
- manifest.json
- package.json
- react/InputSearch.js
- react/components/Input/README.md
- react/components/Input/index.js
- react/components/InputSearch/README.md
- react/components/InputSearch/index.js
Based on https://github.com/vtex/styleguide/tree/feature/search-input
> Add input search

- CHANGELOG.md
- manifest.json
- package.json
- react/components/icon/Edit/index.js
- react/components/icon/Failure/index.js
- react/components/icon/Filter/index.js
- react/components/icon/Help/index.js
- react/components/icon/Success/index.js
- react/components/icon/Warning/index.js
> Fix solid icons display block

- react/components/Table/index.js
- react/components/Table/sampleData.js
> Update table styles to match Figma version

- react/components/Input/index.js
- react/components/Textarea/index.js
> Fix background color of inputs.

- CHANGELOG.md
- react/Slider.js
- react/components/Slider/README.md
- react/components/Slider/Selector.js
- react/components/Slider/index.js
Resolves #319 
Demo: https://lucas--storecomponents.myvtex.com/veiculos/d
> Add slider component

- CHANGELOG.md
- react/MultiSelect.js
- react/components/Dropdown/README.md
- react/components/MultiSelect/DropdownList.js
- react/components/MultiSelect/README.md
- react/components/MultiSelect/Tag.js
- react/components/MultiSelect/index.js
Add multi-select component.
See Issue #61 
Tags can be added by click, tab or enter. Use arrow keys to navigate through options. To remove a tag, one can either click it or use backspace.
> [WIP] Multi-Select Component

- react/IconColumns.js
- react/components/ResourceList/README.md
- react/components/ResourceList/index.js
- react/components/ResourceList/sampleData.js
- react/components/icon/Columns/index.js
- react/components/icon/README.md
- Add hide/show columns option in ResourceList tollbar
> Toggle columns

- CHANGELOG.md
- react/components/EmptyState/index.js
Closes https://github.com/vtex/styleguide/issues/349
> Remove border

- CHANGELOG.md
- react/components/MultiSelect/DropdownList.js
- react/components/MultiSelect/Tag.js
- react/components/MultiSelect/index.js
Tava devendo isso pra @jullyanav faz um tempão, hoje finalmente parei pra implementar esses ajustes. O desenvolvimento do componente foi feito em cima de um desenho muito antigo que o Simoens havia feito. Tudo o que fiz foi adaptar pra estilos mais padrão que temos usado no admin.
Antes
===
Depois
===
> Small visual improvements in Multiselect

- react/docs/Pathline.js
- styleguide.config.js
Show how to import a component using Styleguide with npm and VTEX IO.
> Show import for npm and VTEX IO

- CHANGELOG.md
- react/components/Textarea/index.js
closes https://github.com/vtex/styleguide/issues/331
> Fix border style

- react/components/Input/README.md
Closes https://github.com/vtex/styleguide/issues/219
> Update demo inputs

- CHANGELOG.md
- manifest.json
- package.json
- react/ModalDialog.js
- react/components/Modal/README.md
- react/components/Modal/index.js
- react/components/ModalDialog/README.md
- react/components/ModalDialog/index.js
Add confirm/Cancel options to the modal.
> Add confirmation option

- CHANGELOG.md
- docs/introduction.md
> Fix line height

- package.json
- styleguide.config.js
- yarn.lock
Bump Styleguidist version and add feature to show components version on header
> Update styleguidist and add version number

- CHANGELOG.md
- manifest.json
- package-lock.json
- package.json
- react/components/Badge/README.md
- react/components/Badge/index.js
- react/components/Dropdown/README.md
- react/components/Input/README.md
- styleguide.config.js
- yarn.lock
Closes https://github.com/vtex/styleguide/issues/359
> Add onClick prop

- CHANGELOG.md
- manifest.json
- package.json
- react/IconDensity.js
- react/components/Table/README.md
- react/components/Table/SimpleTable.js
- react/components/Table/Toolbar.js
- react/components/Table/index.js
- react/components/icon/Density/index.js
- react/components/icon/README.md
- Opinionated hover style in Table when there is onRowClick function.
- Insert `density` as prop to Table
- Adds Density control in toolbar (`density` prop inside toolbar shape)
- Adds Density Icon
- [Bonus] Makes Icon Table grid automatic in Icons Readme (now you can just add a new icon on the require object and ta magic is done automatically ✨)
> Enhance Table

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/index.js
Fix table render when schema object deeply changes
> Deep compare schema changes in props

- react/components/Table/index.js
We should run lint before `vtex publish` in deploy command :/
> Add trailing comma dangle

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Input/README.md
- react/components/Input/index.js
- react/components/InputSearch/index.js
- react/components/PasswordInput/index.js
Closes https://github.com/vtex/styleguide/issues/196
> Update prefix and suffix props

- CHANGELOG.md
- manifest.json
- package.json
- react/components/NumericStepper/README.md
- react/components/NumericStepper/index.js
- yarn.lock
Adds lean mode to NumericStepper. Details of the styling might be tweaked later.
Closes https://github.com/vtex/styleguide/issues/393
> NumericStepper lean mode

- CHANGELOG.md
- README.md
- _releasy.json
- manifest.json
- package.json
- react/IconOptionsDots.js
- react/IconVisibilityOff.js
- react/IconVisibilityOn.js
- react/PasswordInput.js
- react/Slider.js
- react/components/icon/OptionsDots/index.js
- react/components/icon/README.md
> Adding options dots Icon

- CHANGELOG.md
- _releasy.json
- manifest.json
- package.json
- react/components/Button/README.md
- react/components/Button/index.js
- react/package.json
- yarn.lock
Adding new type of button named "danger tertiary":
> Add "danger tertiary" Button variation

- CHANGELOG.md
- manifest.json
- package.json
- react/components/PageHeader/README.md
- react/components/PageHeader/index.js
Force the background color to transparent. 
closes https://github.com/vtex/styleguide/issues/387
> Change PageHeader background to transparent

- CHANGELOG.md
- react/components/Dropdown/index.js
> Add missing border to disabled Dropdown state

- react/components/Button/README.md
> Improve Button collapse example

- CHANGELOG.md
- react/components/PageBlock/README.md
- react/components/PageBlock/index.js
- styleguide.config.js
> Add PageBlock component

- CHANGELOG.md
- manifest.json
- package.json
- react/Layout.js
- react/components/Layout/README.md
- react/components/Layout/index.js
- react/components/Table/README.md
- styleguide.config.js
> Add Layout component

- react/components/Layout/README.md
Use PageBlock instead of a Card.
> Fix Layout example to use PageBlock

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Layout/index.js
- Fixes vtex/styleguide/issues/447
> Hotfix fullWidth prop in Layout component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/PageBlock/README.md
Updating pageblock's guidelines in order to prevent its misuse as boxes titles.
> Update read me pageblock

- docs/styles/typography.md
- Add Type token documentation at styles section
- Fix some lint and yarn bugs 
- Clear unused classes
> Add Type token documentation [2]

- .gitignore
- CHANGELOG.md
- manifest.json
- package.json
- react/components/Layout/index.js
- yarn.lock
Prevent the Layout component from not filling the whole height of the page:
> Add heigth class

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/README.md
- react/components/Table/SimpleTable.js
- react/components/Table/index.js
Allow table to go full width and have all columns the same width.
**Before**
**After**
> Add fullwidth prop

- CHANGELOG.md
- manifest.json
- package.json
- react/components/DatePicker/index.js
> Disable keyboard interaction in DatePicker

- react/components/DatePicker/README.md
> Add docs for Datepicker

- react/components/Select/MultiValueRemove.js
- react/components/Select/README.md
- react/components/Select/index.js
- react/components/Select/styles.js
I was checking the current state of the component development and implemented some suggested changes:
- Improves the internal Tag design and creates 3 different sizes based on the Select component size
- Improves microinteractions
- Remove isClearable option prop, it's now always ON
- Improves examples
- Adds documentation
> Select/multiselect - improvements

- .vtexignore
- README.md
- package.json
- react/components/Alert/index.js
- react/components/Alert/index.test.js
- setupTests.js
- yarn.lock
Add first test to the codebase.
> Hello tests

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Conditions/Atoms/ObjectAtom.js
- react/components/EXPERIMENTAL_Conditions/README.md
Make possible to pass extra parameters to Conditions object atom.
> Modify object atom in conditions component to receive extra parameters

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Dropdown/README.md
- react/components/Dropdown/index.js
Allow dropdown to be used inline.
Live example: https://kevin--boticario.myvtex.com/admin/
Screenshots:
> Add inline prop

- CHANGELOG.md
- manifest.json
- package.json
- react/InputCurrency.js
- react/components/Input/README.md
- react/components/InputCurrency/README.md
- react/components/InputCurrency/index.js
- react/package.json
- react/yarn.lock
- styleguide.config.js
- yarn.lock
Add **InputCurrency** new component for monetary input values. It uses [react-number-format](https://www.npmjs.com/package/react-number-format) package to deal with the number formatting.
This closes #213.
> InputCurrency

- react/components/EXPERIMENTAL_Select/index.js
- react/components/Menu/index.js
- react/components/Slider/index.js
- react/components/Table/SimpleTable.js
Small refactors to allow compilation.
> Lint files

- CHANGELOG.md
- react/components/Button/index.js
> Fix button outline when block mode and loading

- CHANGELOG.md
- manifest.json
- package.json
- react/package.json
- react/yarn.lock
- yarn.lock
> Fix package imports

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/README.md
- react/components/Table/Totalizers.js
- react/components/Table/index.js
- react/components/Table/totalizers/TotalizerIcon.js
- react/components/Table/totalizers/TotalizerLabel.js
- react/components/Table/totalizers/TotalizerValue.js
Live: http://10.1.12.74:6060/#/Components/Display/Table
> Add totalizers

- CHANGELOG.md
- manifest.json
- package.json
- react/components/ActionMenu/README.md
- react/components/ActionMenu/index.js
- react/components/Button/index.js
- react/components/ButtonWithIcon/README.md
- react/components/ButtonWithIcon/index.js
- react/components/Dropdown/index.js
- react/components/Input/index.js
- react/components/InputCurrency/index.js
- react/components/InputPassword/index.js
- react/components/InputSearch/index.js
- react/components/Menu/index.js
- react/modules/withForwardedRef.js
- react/package.json
- react/yarn.lock
- yarn.lock
This PR changes the way the `Menu` component is added to the DOM. Now it uses [`react-overlay`](https://github.com/react-bootstrap/react-overlays) to add the `Menu`to the bottom of the DOM.
This closes #505.
> Use react-overlays on ActionMenu

- CHANGELOG.md
- manifest.json
- package.json
- react/EXPERIMENTAL_Select.js
- react/IconClear.js
- react/InputCurrency.js
- react/MultiSelect.js
- react/ToastProvider.js
- react/components/Tabs/Tab.js
In a case of multiple tabs, the current padding is too small, making the reading harder than it should be. So this PR adds a bit more space on the tab horizontal padding.
> Fix horizontal padding on tabs

- CHANGELOG.md
- manifest.json
- package.json
- react/components/ActionMenu/index.js
- react/components/ToastProvider/README.md
- react/components/ToastProvider/ToastManager.js
- react/components/ToastProvider/index.js
> Fix action menu icon compatibility

- CHANGELOG.md
- manifest.json
- package.json
- react/components/DatePicker/README.md
- react/components/DatePicker/index.js
Add ref to **DatePicker** component.
Fixes #576.
> Add forwardedRef to DatePicker component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Select/README.md
- react/components/EXPERIMENTAL_Select/index.js
Add ref to **Select** component.
Fixes #578.
> Add forwardedRef to Select component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/PageHeader/README.md
- react/components/PageHeader/index.js
> Adding a subtitle prop to the pageHeader component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Alert/README.md
- react/components/Alert/index.js
Add forwardedRef to **Alert** component.
Fixes #579.
> Add ref to Alert component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Conditions/Atoms/SubjectAtom.js
- react/components/EXPERIMENTAL_Conditions/Atoms/VerbAtom.js
- react/components/EXPERIMENTAL_Conditions/README.md
- react/components/EXPERIMENTAL_Conditions/Statement.js
Add ref to conditions statement atoms.
> Add ref object to conditions statement (subject, verb and object ref)

- CHANGELOG.md
- manifest.json
- package.json
- react/components/DatePicker/README.md
- react/components/DatePicker/index.js
**Right-aligned:**
<hr>
**Upwards:**
> Add 'align' and 'direction' props to DatePicker

- CHANGELOG.md
- manifest.json
- package.json
- react/components/DatePicker/index.js
**Before**
<kbd>![image](https://user-images.githubusercontent.com/8486092/55181547-a0f05900-516a-11e9-9639-4e08b4a3fdeb.png)</kbd>
<hr>
**After**
<kbd>![image](https://user-images.githubusercontent.com/8486092/55181305-30493c80-516a-11e9-9673-e5dbfb8c648c.png)</kbd>
(Thanks @lbebber ❤️)
> Fix - DatePicker overflow

- CHANGELOG.md
- manifest.json
- package.json
- react/components/DatePicker/index.js
> Fix - DatePicker modifiers warning

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Select/index.js
It adds a max height prop for when the user imports a file into a select and it ends up in a big values container
> Add max height to values container in select

- CHANGELOG.md
- manifest.json
- package.json
- react/components/DatePicker/README.md
- react/components/DatePicker/index.js
> Feature - Date and time range props

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Box/index.js
> Add noPadding prop to Box

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Tag/README.md
- react/components/Tag/index.js
> Add sizes to Tag (small, regular, large)

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Tabs/README.md
- react/components/Tabs/index.js
> Added sticky property to Tabs component

- react/components/RadioGroup/README.md
Just changed from portuguease to english
> Change the RadioGroup label prop to english

- CHANGELOG.md
- manifest.json
- package.json
- react/EXPERIMENTAL_ButtonWithAction.js
- react/components/EXPERIMENTAL_ButtonWithAction/README.md
- react/components/EXPERIMENTAL_ButtonWithAction/index.js
- react/components/Table/Toolbar.js
- styleguide.config.js
This used some feature from `feature/joined-buttons` that is still a WIP by @lbebber.
> Add EXPERIMENTAL_ButtonWithAction

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Checkbox/README.md
- react/components/Checkbox/index.js
- react/components/icon/CheckPartial/index.js
Closes https://github.com/vtex/styleguide/issues/613
> Add CheckboxPartial & partial state

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Tabs/index.js
As title says...
Bug:
Solution:
> Fix partial width tab content

- react/components/Toggle/README.md
> Update toggle docs with new label guidelines

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/SimpleTable.js
- Fix table resize when using fullwidth and the `updateTableKey` prop.
> Fix table resize

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/index.js
as the title says
it resolves this issue: https://github.com/vtex/styleguide/issues/647
prints from before the fix are in the issue  
**After the fix:**
chrome:
firefox:
> add height offset to horizontal scrollbar in Table component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/CheckboxGroup/README.md
Add required props to CheckboxGroup examples on README
Remove the example of a group without any label
Fix example bug:
- Cannot select the group by clicking on the label
- By clicking on the last group label, the first group is selected
Access [CheckboxGroup](https://styleguide.vtex.com/#/Components/Forms/CheckboxGroup) to test the bug and run locally to test the modifications
> Fix CheckboxGroup examples

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/Toolbar.js
Display labels texts.
Labels were not being displayed.
> Fix toolbar labels

- react/components/DatePicker/README.md
> Add known issues list to Datepicker component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/index.js
Prevent an empty space when no toolbar options are set.
`git pull` & `yarn styleguide`
> Remove default toolbar prop

- CHANGELOG.md
- react/components/Table/README.md
Update `Table` bulk actions doc.
Lack of information about the two buttons "select all".
> Update table doc

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Collapsible/index.js
Fix collapsible responsive height when content resizes.
https://asdf--pricingqa.myvtex.com/admin/app/promotions/new
> Fix collapsible height when content resizes

- CHANGELOG.md
- manifest.json
- package.json
- react/components/ModalDialog/README.md
- react/components/ModalDialog/index.js
> Add loading state to ModalDialog

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Checkbox/index.js
- Fixes vtex/styleguide/issues/540
Before this change:
After:
I've added a parent div with `relative` positioning.
> Fixes Checkbox with big label

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Modal/BottomBar.js
- react/components/Modal/TopBar.js
- react/components/Modal/index.js
Fix Modal spacing
Add showBottomBarBorder
Mobile Modal at inStore
Running locally
> Fix Modal spacing and Add showBottomBarBorder

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Totalizer/TotalizerValue.js
Changed import path for totalizer component which was breaking automated tests.
Some automated tests are breaking when using the table component.
> Fix table breaking automated tests

- CHANGELOG.md
- CODEOWNERS
- manifest.json
- package.json
Add CODEOWNERS file to require pull request reviews from at least 1 front-end engineer and 1 designer.
Changes to _styleguide_ that were not approved by the design team.
> Add CODEOWNERS

- CHANGELOG.md
- package.json
What is the purpose of this pull request?
Update vtex-tachyons to latest major.
What problem is this solving?
Some elements like colors have been fixed by designers and are not yet used by the Styleguide.
> Update VTEX tachyons

- CHANGELOG.md
- manifest.json
- package.json
- react/Link.js
- react/components/Link/README.md
- react/components/Link/index.js
- styleguide.config.js
- yarn.lock
Create a Link component, anchor tag.
No Link component.
Pull & `yarn styleguide`
> Add Link component

- CODEOWNERS
Disable component-specific code owners.
Unnecessary need for specific reviewers.
> Disable component specific codeowners

- CHANGELOG.md
- manifest.json
- package.json
- react/TimePicker.js
- react/components/DatePicker/README.md
- react/components/DatePicker/index.js
- react/components/DatePicker/react-datepicker.global.css
- react/components/TimePicker/README.md
- react/components/TimePicker/index.js
- styleguide.config.js
- yarn.lock
This component uses the **DatePicker** component as the base. That way every new feature/fix we implement in the **DatePicker** we will also be applied to the **TimePicker** component.
Closes #65.
> Add TimePicker component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Collapsible/index.js
[Click here to access the workspace.](https://waza--storecomponents.myvtex.com/admin/collections/create)
> Remove animation of the Collapsible when it is mounted for the FIRST TIME

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Collapsible/index.js
[Workspace.](https://vitoria--storecomponents.myvtex.com/admin/)
> Fix collapsible arrow position

- CHANGELOG.md
- manifest.json
- package.json
- react/IconInfo.js
- react/components/Button/index.js
- react/components/ColorPicker/ColorHistory.js
- react/components/icon/Info/index.js
- react/components/icon/README.md
- react/docs/Pathline.js
- react/modules/deprecated.js
The `styleguide` is missing `IconInfo`
> Added IconInfo

- CHANGELOG.md
- manifest.json
- package.json
- react/IconPrinter.js
- react/components/Table/index.js
- react/components/icon/Printer/index.js
- react/components/icon/README.md
> Add printerIcon

- CHANGELOG.md
- README.md
- manifest.json
- package.json
- Now to launch fixes for 8.x we must use the 8.x branch, and 9.x becomes our master 🙏 
- All of the pain in releasing always 2 versions per fix/feature
> Merge 9.x into master

- CHANGELOG.md
- manifest.json
Forgot to release before merging 🤦‍♂
> Release v9.73.2

- CHANGELOG.md
- manifest.json
- package.json
- Gets changes from vtex/styleguide/pull/754 lost in the confusion of merges and releases from earlier.
- Updates version with changes from the PR lost in the previous merges
> Updates CHANGELOG

- CHANGELOG.md
- manifest.json
- package.json
- react/components/FloatingActionBar/index.tsx
Fix button reference which broke the latest npm release
> Fix button reference which broke the latest npm release

- react/components/Link/index.js
Remove unused `{` from `Link` component `className`. 
Check the final render.
**Before:** `{pointer c-link hover-c-link active-c-link no-underline underline-hover `
**After:** `pointer c-link hover-c-link active-c-link no-underline underline-hover `
> Remove spare bracket

- react/components/Toggle/index.js
> Revert "fix toggle onclick bug"

- README.md
- react/components/Button/index.js
- react/components/ColorPicker/ColorHistory.js
- react/docs/Pathline.js
- react/modules/deprecated.js
Add disclaimer to explain why we have two majors and how to maintain them and fix some lint issues.
> Fix add two majors disclaimer

- CHANGELOG.md
- react/components/Checkbox/index.js
In some cases, this prop is not necessary on the Checkbox, so it should not be required.
[Workspace.](https://vitoria--storecomponents.myvtex.com/admin/collections/850/)
> Update the value prop to be not required in the Checkbox

- react/components/Slider/Selector.js
- react/components/Slider/index.js
Fix the sizing of the component
Add a relative size
run localy the branch
Take a look on the issue #795
> Fix slider size issue #795

- CHANGELOG.md
- manifest.json
- package.json
- react/EXPERIMENTAL_Table.ts
- react/EXPERIMENTAL_useTableState.ts
> Fixed: default export of useTableState from EXPERIMENTAL_TableV2

- CHANGELOG.md
- manifest.json
- package.json
Publish unreleased changes in master
> Release v9.77.4

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Input/index.js
Fix the Input's disabled background.
Space between background color & borders.
checkout & run styleguide
Before:
After:
> Fix input disabled background

- CHANGELOG.md
- manifest.json
- package.json
- Last deploy had no `lib` folder on npm package.
- The one mentioned above
- see package in npm unpkg
> Release v9.78.1

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Conditions/index.tsx
- fix `hideOperator` default value
- it's wrong
> Fix Conditions default props of hide operator

- CHANGELOG.md
- manifest.json
- package.json
- react/components/ToastProvider/Toast.js
Add css classname to the toast container. Solves this https://github.com/vtex-apps/store-discussion/issues/99
> Add css classname to the toast container

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Input/index.js
Same as https://github.com/vtex/styleguide/pull/844 for 8.x
> Fix readonly styles

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Modal/index.js
- react/components/Tooltip/TooltipPopup.tsx
- react/components/utils/zIndex.ts
> Set Tooltip z-index to avoid being shadowed by other components

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/Styled.tsx
- react/components/EXPERIMENTAL_Table/index.tsx
- react/components/EXPERIMENTAL_Table/typings.d.ts
The table rows may be clickable.
Clone the repo and `yarn install && yarn start`
> EXPERIMENTAL_TableV2 Clickable Rows

- CHANGELOG.md
- manifest.json
- package.json
- styleguide.config.js
Closes https://github.com/vtex/styleguide/issues/813
> Remove doc from config

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Input/Input.css
Closes https://github.com/vtex/styleguide/issues/789
Before:
After:
> Add css placeholder

- CHANGELOG.md
- react/components/FilterBar/FilterTag.js
- react/components/FilterBar/index.js
- react/components/Table/Toolbar.js
Applies some design corrections and improvements in the Table component.
Fixes #851
---
---
---
> [Filters] Design corrections and improvements

- CHANGELOG.md
- manifest.json
- package.json
- react/EXPERIMENTAL_useTableBulkActions.ts
- react/components/EXPERIMENTAL_Table/BulkActions.tsx
- react/components/EXPERIMENTAL_Table/BulkActions/Checkbox.tsx
- react/components/EXPERIMENTAL_Table/BulkActions/index.tsx
- react/components/EXPERIMENTAL_Table/Checkbox.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
- react/components/EXPERIMENTAL_Table/Pagination.tsx
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/Styled.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonGroup.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/Container.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/InputCustom.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/InputSearch.tsx
- react/components/EXPERIMENTAL_Table/constants.ts
- react/components/EXPERIMENTAL_Table/context.ts
- react/components/EXPERIMENTAL_Table/errors.ts
- react/components/EXPERIMENTAL_Table/hooks/useTableBulkActions.tsx
- react/components/EXPERIMENTAL_Table/index.tsx
- react/components/EXPERIMENTAL_Table/typings.d.ts
`EXPERIMENTAL_TableV2` may have bulk actions
`yarn start`
> Add Bulk Actions to EXPERIMENTAL_TableV2

- CHANGELOG.md
- react/components/Button/index.js
Fixes https://github.com/vtex/styleguide/issues/810
> Fixes hover in collapsed tertiary buttons

- CHANGELOG.md
- manifest.json
- package.json
- react/components/ModalDialog/README.md
- react/components/ModalDialog/index.js
- ditto.
- Now you indicate destructive actions on ModalDialog.
> Add isDangerous prop to ModalDialog

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_TableTree/README.md
- react/components/EXPERIMENTAL_TableTree/hooks/useTableTreeCheckboxes.tsx
This prop allows items to render already checked.
No need
> Added checked prop to EXPERIMENTAL_useTableTreeCheckboxes

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/FilterBar.tsx
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/constants.ts
- react/components/EXPERIMENTAL_Table/index.tsx
- react/components/EXPERIMENTAL_TableTree/index.tsx
- react/components/FilterBar/index.js
`Table` and `TableTree` may filter it's data.
> Add FilterBar component to EXPERIMENTAL_Table

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
Same as https://github.com/vtex/styleguide/pull/872 for `8x`
> Fixes hover colors of tertiaries

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Select/index.js
Continuation of #895 for `8.x`
> Fix/add multiple default values proptype 8.x

- CHANGELOG.md
- react/components/Input/README.md
- react/components/Input/index.js
- react/components/InputButton/README.md
- react/components/InputButton/index.js
- styleguide.config.js
Creates the InputButton component.
It improves the experience of using a one-input-form.
Details in Figma: https://www.figma.com/file/2t4pmT0LUkPYbohaSxxJ7k/03-InputButton?node-id=0%3A1
Run `yarn styleguide` and go to http://localhost:6060/#/Components/Forms/InputButton.
> New InputButton component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/index.js
Fixes https://github.com/vtex/styleguide/issues/788
`checkout` & `yarn styleguide`
Before:
After:
> Update label vertical alignment

- CHANGELOG.md
- manifest.json
- package.json
- react/SelectableCard.ts
- react/components/FloatingActionBar/index.tsx
- react/components/RadioGroup/README.md
- react/components/SelectableCard/README.md
- react/components/SelectableCard/index.tsx
- styleguide.config.js
This Component is required for the new category view form in Admin Catalog.
[Running workspace](https://thalyta1--storecomponents.myvtex.com/admin/categories/create)
> New Component Selectable Card

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Box/README.md
- react/components/Box/index.tsx
Solves https://github.com/vtex/styleguide/issues/453
Having a title in a Box is a very common thing and each developer has been implementing it a little differently.
> Adds title prop to Box

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/index.js
Update description for the **Table**'s `dynamicRowHeight` prop.
This is meant to address issue #910 
No tests needed
None
> Update description for the dynamicRowHeight field

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
Hooks must always be called at the top level of the component.
Clone the repo `yarn && yarn start`
No need.
> Fix hooks errors on EXPERIMENTAL_Table

- CHANGELOG.md
- docs/charts.md
- manifest.json
- package.json
- react/BarChart.tsx
- react/components/EXPERIMENTAL_Charts/BarChart/README.md
- react/components/EXPERIMENTAL_Charts/BarChart/constants.ts
- react/components/EXPERIMENTAL_Charts/BarChart/index.tsx
- react/components/EXPERIMENTAL_Charts/BarChart/sampleData.js
- react/components/EXPERIMENTAL_Charts/LineChart/README.md
- react/components/EXPERIMENTAL_Charts/LineChart/constants.ts
- react/components/EXPERIMENTAL_Charts/LineChart/index.tsx
- react/components/EXPERIMENTAL_Charts/commonProps.ts
- react/components/EXPERIMENTAL_Charts/helpers.ts
- react/components/EXPERIMENTAL_Charts/typings.d.ts
- styleguide.config.js
- yarn.lock
as the title says
`yarn install && yarn start`
> Add barchart

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Button/README.md
- react/components/Button/index.js
Fix collapse & primary styles.
> Fix buttons

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Totalizer/README.md
- react/components/Totalizer/TotalizerLabel.js
- react/components/Totalizer/TotalizerValue.js
- react/components/Totalizer/index.js
Add inverted prop.
Weight difference in some situations.
> Add inverted prop

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Totalizer/README.md
Fix the inconsistencies between Totalizer & Totalizers.
> Fix documentation

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Totalizer/README.md
- react/components/Totalizer/index.js
Add new prop.
Need for horizontal layout.
> Add horizontalLayout prop

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
- react/components/EXPERIMENTAL_useCheckboxTree/types.ts
Display the last toggled item at `onToggle` function
clone the repo and `yarn && yarn start`
> Added last toggled item

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
Avoid returning stale values on callbacks and memos.
[Running workspace](https://matheusps--cosmetics1.myvtex.com/admin/app/collections/create/)
> Fixed useCheckboxTree hooks dependencies

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
- react/components/EXPERIMENTAL_Table/index.tsx
[Running workspace](https://matheusps--cosmetics1.myvtex.com/admin/app/collections/523)
Dynamic key generation makes react to skip the diffing algorithm at the reconciliation process.
> Fixed rendering problems due to dynamic key generation on EXPERIMENTAL_Table.

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
The `lastToggledItem` is useful in a bunch of scenarios.
> Return lastToggledItem of EXPERIMENTAL_useCheckboxTree

- CHANGELOG.md
- manifest.json
- package.json
- react/components/AutocompleteInput/hooks.ts
- react/components/Conditions/index.tsx
- react/components/EXPERIMENTAL_Charts/helpers.ts
- react/components/EXPERIMENTAL_Charts/typings.d.ts
- react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
- react/components/EXPERIMENTAL_Table/LineActions.tsx
- react/components/EXPERIMENTAL_Table/Pagination.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/Button.tsx
- react/components/EXPERIMENTAL_Table/index.tsx
- react/components/EXPERIMENTAL_useCheckboxTree/constants.ts
- react/components/EXPERIMENTAL_useCheckboxTree/types.ts
- react/components/Tooltip/hooks.ts
Respect eslint warnings can prevent bugs.
`yarn && yarn lint`
> Fix eslint warnings

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/README.md
- react/components/EXPERIMENTAL_Table/Totalizer.tsx
- react/components/EXPERIMENTAL_Table/constants.ts
- react/components/EXPERIMENTAL_Table/index.tsx
- react/components/Totalizer/index.js
The new table must have totalizers.
> Added Totalizer to EXPERIMENTAL_Table

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonColumns.tsx
The table was breaking on importing from npm.
No need
> Fix EXPERIMENTAL_Table npm import

- react/components/AutocompleteInput/Option.tsx
- react/components/AutocompleteInput/SearchInput/index.tsx
- react/components/EXPERIMENTAL_Table/BulkActions/Actions.tsx
- react/components/EXPERIMENTAL_Table/BulkActions/Tail.tsx
- react/components/EXPERIMENTAL_Table/BulkActions/index.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Cell.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
- react/components/EXPERIMENTAL_Table/DataTable/index.tsx
- react/components/EXPERIMENTAL_Table/FilterBar.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/Button.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonGroup.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/InputAutocomplete.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/index.tsx
- react/components/Pagination/index.js
- react/components/Totalizer/index.js
Standardize classnames imports.
`#trivial`: there's no need for a `CHANGELOG.md` since no feature has been added or removed, nor bugs where fixed.
Resolves #1006
Go into this branch and test the components that have been changed to see if they still work.
> Standardize classnames imports

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/Toolbar/Button.tsx
- react/components/EXPERIMENTAL_Table/constants.ts
[Running workspace](https://thalyta--storecomponents.myvtex.com/admin/collections/create/)
Before:
After:
> Fix margin when the download button is disabled

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Table/SwitchablePagination.js
- react/components/Table/index.js
There are some errors in the `Table` that are displayed on the `console`. The idea of ​​this PR is to make the console as clean as possible by correcting bugs.
- The `SwitchablePagination` component receives a prop called `enabled` which expects it to be of type `boolean`, however it was receiving an `object`.
- Props are required for the `Pagination` component but should not be required for the `SwitchablePagination` component since it renders only if `enabled` is` true`.
> Fix Errors in Table

- CHANGELOG.md
- manifest.json
- package.json
Fix my earlier pull request not being released before merge 🙃
> Release v9.106.3

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Cell.tsx
- react/package.json
- react/yarn.lock
- yarn.lock
✨ Now `EXPERIMENTAL_Table` cell to have no dependencies.
🚫 Removed `styled-components` dependency.
Reduce the table bundle size.
> Refactoring EXPERIMENTAL_Table Cell

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Checkbox/index.js
Add 3 new css handles on the checkbox. This PR is similar to this one https://github.com/vtex/styleguide/pull/997
https://github.com/vtex-apps/store-discussion/issues/181
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing?map=c,c&order=OrderByReleaseDateDESC&query=/apparel---accessories/clothing)
inspect the filters checkbox.
> Added some checkbox css handles.

- CHANGELOG.md
- react/components/FilterBar/FilterTag.js
- react/components/FilterBar/index.js
- scripts/entrypoints.js
- scripts/version.js
as the title says.
Avoid use css selectors in test implementations.
[Workspace](https://mariana--cosmetics1.myvtex.com/admin/collections/1006/).
> Add test id for MoreOptions button

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Checkbox/index.js
As the title says. The feature was merged without a release.
> Fix release

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/README.md
> Added EXPERIMENTAL_Table features docs

- CHANGELOG.md
- manifest.json
- package.json
- react/components/icon/IconBase.js
This file was ignored by the gitignore.
> Add misssing IconBase file

- CHANGELOG.md
- README.md
- manifest.json
- package.json
- react/components/icon/IconBase.js
Add more check to document for prevent undefined
> Add more check to document for prevent undefined

- CHANGELOG.md
- manifest.json
- package.json
Github was unstable when making a release, for some reason the `push` not worked, so so the necessary changes were not made to the changelog, manifest and package.json 
[Running workspace](https://wksquebrada--cosmetics1.myvtex.com/admin/collections/1077/)
> Fix changelog, manifest and package.json

- CHANGELOG.md
- manifest.json
- package.json
Add missing tag/release forgotten on previous PR (#1055)
> Release v9.112.4

- CHANGELOG.md
- manifest.json
- package.json
What is the purpose of this pull request?
Add missing tag/release forgotten on previous PR (#1040)
> Release v9.112.5

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/README.md
The migration guide is important for users coming from the previous table version.
> Added [COMPOSITION OVER OBJECT PROPS] section at EXPERIMENTAL_Table docs

- CHANGELOG.md
- manifest.json
- package.json
- react/components/FilterBar/FilterTag.js
- react/components/FilterBar/Menu.js
- react/components/FilterBar/index.js
[Running workspace](https://waza--cosmetics1.myvtex.com/admin/collections/)
To facilitate the tests of the Filters.
> Add testId prop in the Filter options

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/DataTable/Cell.tsx
- react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
[Running Workspace](https://cellrerender--cosmetics1.myvtex.com/admin/collections)
Check the update highlights
Before:
After
> Fixed unecessary Cell rerender on EXPERIMENTAL_Table

- .github/workflows/test.yml
- package.json
- react/components/Alert/index.test.js
- react/components/Button/__snapshots__/index.test.tsx.snap
- react/components/Button/index.test.tsx
- yarn.lock
Add snapshot tests to Button so we can keep track of changes in style and avoid breaking stores' customizations.
Motivation of this PR is to guarantee that #1068 doesn't break our Button.
> **There's no changelog change because it doesn't change our API**
Run tests 😅
> #trivial Feature tests

- CHANGELOG.md
- react/components/Checkbox/README.md
- react/components/Checkbox/index.js
Fix #799 
Run this project locally and go to the Checkbox page. Make sure that when the `size` prop is passed, the text size changes.
> Add size prop to checkbox

- .github/workflows/test.yml
- CHANGELOG.md
Run Github CI for tests in features branch
Tests in `features` branch
> Github CI for tests in features branch

- react/components/Alert/index.js
- react/components/Alert/index.test.js
- yarn.lock
#trivial Fix eslint errors #1082
Fix eslint in alert component
`yarn lint`
> Fix eslint in alert component

- CHANGELOG.md
- react/components/Checkbox/index.js
Add a new class to Checkbox component.
That class is needed to fix this issue:
https://github.com/vtex-apps/store-discussion/issues/220
https://doru--dacris.myvtex.com/articole-de-birou/organizare-si-arhivare
> Add missing class to checkbox label

- CHANGELOG.md
- manifest.json
- package.json
Ops, release https://github.com/vtex/styleguide/pull/1093
> Release v9.112.18

- CHANGELOG.md
- manifest.json
- package.json
- react/components/EXPERIMENTAL_Table/hooks/useTableMeasures.tsx
Fixing this error:
[Fixed workspace](https://thay2--cosmetics1.myvtex.com/wedemo)
[Broken workspace](https://thay--cosmetics1.myvtex.com/wedemo)
> Fix EXPERIMENTAL_useTableMeasures SSR errors

- react/components/Modal/TopBar.js
- react/components/ModalDialog/index.js
#trivial Fix Eslint errors #1082
`yarn lint`
> Fix eslint errors in Modal and ModalDialog

- react/components/Dropzone/index.js
> #trivial  fixed Dropzone eslint issues

- react/components/SelectableCard/index.tsx
- react/components/Slider/Selector.js
- react/components/Slider/index.js
- react/components/ToastProvider/Toast.js
- react/components/ToastProvider/ToastManager.js
- react/components/ToastProvider/index.js
#trivial fix Eslint errors #1082 
`yarn & yarn start`
`yarn lint`
> fix eslint errors in SelectableCard, Slider and ToastProvider

- react/components/FilterBar/FilterTag.js
- react/components/FilterBar/Menu.js
fixes for: `FilterBar/Menu` & `FilterBar/FilterTag` #1082
> #trivial: fix filterbar eslint issues

- react/components/EXPERIMENTAL_Table/context/testing.tsx
- yarn.lock
`features` and `master` must sync
> Merge master and features together

- react/components/EXPERIMENTAL_Conditions/Atoms/ObjectAtom.js
- react/components/EXPERIMENTAL_Conditions/Atoms/SubjectAtom.js
- react/components/EXPERIMENTAL_Conditions/Atoms/VerbAtom.js
- react/components/EXPERIMENTAL_Conditions/README.md
- react/components/EXPERIMENTAL_Conditions/Statement.js
- react/components/EXPERIMENTAL_Conditions/StrategySelector.js
- react/components/EXPERIMENTAL_Conditions/index.js
clone the repo and `yarn && yarn start`
> #trivial fix: 🐛 experimental conditions eslint issues

- CHANGELOG.md
- react/components/Tabs/Tab.js
- react/components/Tabs/index.js
- react/components/Tabs/index.test.tsx
as the title says
Related issue #1083 
`yarn test`
> Tests for the Tabs component

- CHANGELOG.md
- manifest.json
- package.json
- react/components/AutocompleteInput/Option.tsx
Master and features must synchronize.
> Sync master and features

- package.json
- react/components/Spinner/__tests__/__snapshots__/index.test.js.snap
- react/components/Spinner/__tests__/index.test.js
- yarn.lock
related issue #1083 
`yarn test`
> #trivial test: 💍 spinner component

- CHANGELOG.md
- react/components/Dropdown/index.js
As title says.
Described at #1131
> Fixed Dropdown's selected option when value is undefined

- react/components/ButtonPlain/README.md
Remove warnings and add functionality to the last example of ButtonPlain documentation.
> Fix warnings and examples #trivial

- react/components/NumericStepper/README.md
Add functionality to last example of the NumericStepper.
Lack of functionality.
> Fix NumericStepper example #trivial

- react/components/DatePicker/README.md
- react/components/Pagination/README.md
- react/components/Textarea/README.md
- react/components/Tooltip/README.md
- react/components/Totalizer/README.md
Update several i18n flaws and enforce english as the main language.
Part of https://github.com/vtex/styleguide/issues/1124
> Fix/doc i18n #trivial

- react/components/Link/README.md
Change Link documentation.
Weak example.
> Update Link examples #trivial

- react/components/Divider/README.md
Change Divider documentation.
Weak example.
> Update Divider examples #trivial

- react/components/Card/README.md
Change Card documentation.
Non eCommerce related documentation.
> Update Card examples #trivial

- CHANGELOG.md
- react/components/Totalizer/TotalizerIcon.js
- react/components/Totalizer/TotalizerLabel.js
- react/components/Totalizer/TotalizerValue.js
- react/components/Totalizer/index.js
Add test-ids attributes.
Lack of reference points for e2e tests.
> Add testids

- react/components/Dropzone/README.md
Fix Dropzone examples.
Non functional examples and lack of consistency.
> Fix Dropzone examples

- react/components/InputCurrency/README.md
Fix inputCurrency non functional examples.
> Fix inputCurrency examples

- CHANGELOG.md
- manifest.json
- package.json
> 2020-04-02
💄Fix outdated link and references to ProgressBar in docs #1123
💄Fix Dropzone examples #1141
💄Update Card examples #1125
💄Update Divider examples #1126
💄Update Link examples #1127
💄Fix/doc i18n #1128
🐞Fixed Dropdown's selected option when value is undefined #1132
🐞Fix outline on ButtonGroup #1133
💄Fix warnings and examples #1134
💄Fix NumericStepper example #1135
🛠Add testids #1137
🆕 Spread react-select props #1138
🐞Fix table v2 header click #1139
💄Fix inputCurrency examples #1140
> Release v9.112.28

- react/components/Button/__snapshots__/index.test.tsx.snap
- react/components/Button/index.test.tsx
- react/components/Button/index.tsx
> #trivial fix button and button tests eslint issues

- react/components/Collapsible/README.md
Add eCommerce related example instead of weak text.
part of https://github.com/vtex/styleguide/issues/1149 and https://github.com/vtex/styleguide/issues/1124
> Fix collapsible example #trivial

- react/components/Box/README.md
Update example.
Remove lorem ipsum text.
> Update Box example

- react/components/EXPERIMENTAL_Table/Sections/Loading.tsx
- react/components/ModalDialog/__snapshots__/index.test.tsx.snap
- react/components/Spinner/__tests__/__snapshots__/index.test.js.snap
- react/components/Spinner/index.tsx
- styleguide.config.js
> #trivial Rewrite Spinner component to typescript

- react/components/DatePicker/README.md
- react/components/Totalizer/README.md
Fix examples.
Wrong functionality of Datepickers and BRL currencies in Totalizer.
> Fix/examples #trivial

- react/components/EXPERIMENTAL_Table/Toolbar/ButtonGroup.tsx
As the title says. #1082 #trivial
> [Experimental_table-ButtonGroup] Fix lint errors

- react/components/Modal/README.md
Update Modal examples.
Lorem ipsum text and weak examples. It also introduces eCommerce themed examples.
> Update modal examples #trivial

- CHANGELOG.md
- manifest.json
- package.json
> 2020-04-09
🛠Add 'fit' prop to PageBlock and Box components #1151
🆕Conditions layout #1152
🐞Add missing namespaced CSS classes to NumericStepper #1153
✏️ Fix/examples #trivial #1145
✏️ Fix collapsible example #trivial #1155
✏️ Update Box example #1162
✏️ Update modal examples #trivial #1164
> Release v9.113.1

- react/components/ModalDialog/README.md
Update `ModalDialog` examples.
Lorem ipsum examples.
> Update examples #trivial

- react/components/Dropdown/README.md
Update `Dropdown` examples.
Non functional examples and lack of e-commerce themed values.
> Update Dropdown examples

- CHANGELOG.md
- react/components/Dropdown/index.js
Add mobile verification.
Duplicated option.
Before:
After:
I'll need someone with an IOs device to test it.
> Add mobile verification

- CHANGELOG.md
- manifest.json
- package.json
> 2020-04-28
🐞 Fix autocomplete input custom option example #1174
🆕 Feature/ Allow units multiplier in numeric stepper component #1173
> Release v9.114.0

- CHANGELOG.md
- manifest.json
- package.json
> 2020-04-30
🛠 Remove tooltip popup max-height #1182
🆕 Add container prop to Tooltip component #1183
🐞 Fix bug when trying to modify the entry when an option is selected in AutocompleteInput #1179
🛠 Remove ActionMenu and Menu default fixed width #1178
> Release v9.115.0

- react/components/Alert/README.md
Update `Alert` examples.
There are mixed `alert` examples without e-commerce context. Also, we don't properly explain each component variant usage.
> Update Alert docs #trivial

- react/components/Tabs/README.md
Update `Tabs` examples.
Non functional examples.
> Update Tabs examples

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Alert/README.md
- react/components/ColorPicker/README.md
- react/components/RadioGroup/README.md
- react/components/RadioGroup/index.js
- react/components/Tabs/README.md
Group the fixes and trivials for the next release
PRs:
#1192 by @jonathasbsouza
#1187, #1188  by @kevinch 
#1191 by @laerc
> Chore/release 9.116.0

- CHANGELOG.md
- react/utilities/docs/useDisclosure.md
- react/utilities/index.ts
- styleguide.config.js
Some components deal with the scenario of open, close, and toggle behavior.
> Add useDisclosure hook

- react/components/Table/README.md
Update `Table` examples.
Portuguese i18n.
> Fix Table examples #trivial

- CHANGELOG.md
- react/components/Slider/index.js
> added vtex css classes on slider range values

- CHANGELOG.md
- manifest.json
- package.json
> 2020-05-14
🆕 Multi select error props #1195
🆕 Add 'tabIndex' prop to 'Button' #1197
🛠 added vtex css classes on slider range values #1199
✏️ Fix Table examples #trivial #1186
✏️ Update examples #trivial #1185
> Release v9.118.0

- .codesandbox/ci.json
- package.json
Added codesandbox CI
It makes it easier to create examples for PR's.
> #trivial ci: 🎡 codesandbox

- CHANGELOG.md
- react/components/Checkbox/index.js
Add `vtex-checkbox__box-wrapper`, `vtex-checkbox__box`, and `vtex-checkbox__input` handles to CheckBox.
[Running workspace](https://breno--storeido.myvtex.com/tutti-i-prodotti?__bindingAddress=www.ido.it/it)
Make it possible to customize it in Store Framework.
Open the workspace and check the HTML of the checkboxes.
> Add checkbox CSS handles

- CHANGELOG.md
- react/components/FilterBar/FilterTag.js
- react/components/FilterBar/index.js
- react/components/Statement/Atoms/SubjectAtom.tsx
- react/components/Statement/Atoms/VerbAtom.tsx
- react/components/Statement/index.tsx
[Running workspace](https://emptyatom--storecomponents.myvtex.com/admin/collections/1938/)
Before this change:
After this change:
> Render empty span if atom has no value

- react/components/EXPERIMENTAL_Select/README.md
Add an example of a grouped Select.
It is already possible to create a grouped Select, but there was no documentation on how to create it.
n/a
#trivial
> Add example of a grouped select

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Statement/index.tsx
#1203 Make alert accessible by @felippenardi 
#1204 Add checkbox CSS handles by @klzns 
#1205 Add example of a grouped select  by @ericreis
> Release v9.119.0

- react/components/ColorPicker/ColorHistory.js
- react/components/ColorPicker/HexInput.js
- react/components/ColorPicker/index.js
> #trivial Fix ColorPicker eslint issues

- react/components/DatePicker/index.js
- react/components/Dropdown/index.js
As the title says 
Depends on #1209 
#1082
> #trivial Fix Datepicker & Dropdown lint

- react/components/Table/BulkActions.js
- react/components/Table/CheckboxContainer.js
- react/components/Table/SimpleTable.js
- react/components/Table/Toolbar.js
- react/components/Table/index.js
It's a lightweight fix since we will deprecate this component in the near future. Some issues were simply disabled. 
#1082
> #trivial Fix table v1 eslint issues

- react/components/EXPERIMENTAL_Select/MultiValueRemove.js
- react/components/EXPERIMENTAL_Select/index.js
> Fix experimental select lint issues

- react/EXPERIMENTAL_Conditions.js
- react/components/index.js
Fixes camelcase issues on `index` & `Conditions` export files.
issue #1082
> #trivial Fix EXPERIMENTAL exports lint

- codemod/button-v4.js
> #trivial Fix codemod lint issues

- CHANGELOG.md
- manifest.json
- package.json
Remove trailing space from numericStepper when suffix doesn't exist #1218
> Release v9.119.1

- CHANGELOG.md
- manifest.json
- package.json
Add forwardedRef to Textarea #1217
Fix dropdown background on error and border color on focus #1220
Fix AutocompleteInput disabled style #1221
Fix Checkbox forwardedRef not accepting function refs #1225
Feature/cell transition #1237
Add disabled prop to FilterBar #1238
> Release v9.120.0

- CHANGELOG.md
- react/components/Checkbox/index.js
- react/components/Checkbox/index.test.js
> Do not break if ref is not present

- CHANGELOG.md
- manifest.json
- package.json
Do not break if ref is not present #1240
> Release v9.120.1

- react/components/EXPERIMENTAL_Table/BulkActions/Actions.tsx
- react/components/EXPERIMENTAL_Table/BulkActions/Tail.tsx
- react/components/EXPERIMENTAL_Table/BulkActions/index.tsx
- react/components/EXPERIMENTAL_Table/Sections/Cell.tsx
- react/components/EXPERIMENTAL_Table/Sections/Loading.tsx
- react/components/EXPERIMENTAL_Table/Sections/Row.tsx
- react/components/EXPERIMENTAL_Table/Sections/Tbody.tsx
- react/components/EXPERIMENTAL_Table/Sections/Thead.tsx
- react/components/EXPERIMENTAL_Table/Sections/index.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/Button.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonColumns.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonDensity.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonExtraActions.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonNewLine.tsx
- react/components/EXPERIMENTAL_Table/Toolbar/PopoverMenu.tsx
- react/components/EXPERIMENTAL_Table/context/body.tsx
- react/components/EXPERIMENTAL_Table/context/measures.tsx
- react/components/EXPERIMENTAL_Table/context/testing.tsx
- react/components/EXPERIMENTAL_Table/hooks/useTableMeasures.tsx
- react/components/EXPERIMENTAL_Table/hooks/useTableMotion.ts
- react/components/EXPERIMENTAL_Table/hooks/useTableSort.ts
- react/components/EXPERIMENTAL_Table/hooks/useTableVisibility.ts
- react/components/EXPERIMENTAL_Table/index.tsx
- react/components/EXPERIMENTAL_Table/types.ts
As the title says. Related issue #1082
> #trivial Fix exp table eslint issues

- CHANGELOG.md
- react/components/Slider/index.js
Add new CSS handle to solve this issue: https://github.com/vtex-apps/search-result/issues/369
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/)
> Add `vtex-slider__base-internal` CSS handle

- CHANGELOG.md
- manifest.json
- package.json
> Release v9.121.0

- react/components/Textarea/index.js
> #trivial Fix textarea lint issues

- react/components/AutocompleteInput/Option.tsx
- react/components/AutocompleteInput/SearchInput/index.tsx
- react/components/AutocompleteInput/index.tsx
> #trivial Fix autocomplete lint issues

- react/components/Tooltip/Portal.tsx
- react/components/Tooltip/TooltipPopup.tsx
- react/components/Tooltip/hooks.ts
- react/components/Tooltip/index.tsx
- react/components/Tooltip/tooltip.stories.tsx
- react/components/Tooltip/utils/dom.ts
- react/tsconfig.json
> #trivial Fix tooltip eslint issues

- CHANGELOG.md
- react/components/ModalDialog/index.js
[Running workspace](https://fixinactivecolor--cosmetics1.myvtex.com/admin/app/collections/)
> Add ModalDialog testids

- CHANGELOG.md
- manifest.json
- package.json
> Release v9.122.0

- CHANGELOG.md
- manifest.json
- package.json
> Release v9.124.0

- CHANGELOG.md
- manifest.json
- package.json
> Release v9.124.1

- CHANGELOG.md
- react/components/EXPERIMENTAL_Select/README.md
- react/components/EXPERIMENTAL_Select/index.js
> fix select menu position as a prop

- CHANGELOG.md
- manifest.json
- package.json
> Release v9.124.2

- CHANGELOG.md
- react/components/Dropdown/index.js
Make it possible to customize the CSS of the dropdown.
n/a
n/a
> Add vtex-dropdown__container CSS handle

- docs/designing.md
- docs/developing.md
- docs/guides.md
- docs/introduction.md
- docs/styles/typography.md
- react/components/Alert/README.md
- react/components/AutocompleteInput/README.md
- react/components/Button/README.md
- react/components/Card/README.md
- react/components/CheckboxGroup/README.md
- react/components/ColorPicker/README.md
- react/components/DatePicker/README.md
- react/components/EXPERIMENTAL_Table/docs/Features.md
- react/components/InputButton/README.md
- react/components/InputSearch/README.md
- react/components/Link/README.md
- react/components/Modal/README.md
- react/components/Table/README.md
- react/components/Tabs/README.md
- react/components/ToastProvider/README.md
- react/components/Totalizer/README.md
The purpose is to correct minor spelling errors in the documentation.
Minor spelling errors.
> Fixing minor spelling mistakes

- CHANGELOG.md
- manifest.json
- package.json
> Release v9.125.0

- CHANGELOG.md
The modified entry should be in `Fixed` section.
> Fix CHANGELOG.md message

- CHANGELOG.md
- react/components/Tooltip/Portal.tsx
This was causing a error in console that I'm not sure should happen (but I think not).
[Running workspace](https://fixproptype--storecomponents.myvtex.com/admin/collections/)
Check that the warning doesn't show,
Before
After
> Fix Proptype assign

- CHANGELOG.md
- manifest.json
- package.json
- `accept`, `minSize` and `maxSize` props to `Dropzone` component.
> Release v9.127.0

- CHANGELOG.md
- react/components/EXPERIMENTAL_Table/Toolbar/ButtonNewLine.tsx
- react/components/icon/Plus/index.js
- react/components/icon/Plus/index.tsx
> Fix plus icon size and color

- CHANGELOG.md
- manifest.json
- package.json
- `onClick` prop to `ActionMenu` component.
- **Plus** icon size and color.
- `AutoCompleteInput` padding-right when `ClearInputIcon` is shown.
- Checkbox alignment with large texts
> Release v9.128.0

- CHANGELOG.md
- manifest.json
- package.json
- **Plus** icon solid alignment.
> Release v9.128.1

- CHANGELOG.md
- react/components/Collapsible/README.md
- react/components/Collapsible/index.js
- react/components/FilterOptions/FilterColapsible.js
- react/components/FilterOptions/README.md
> Fix FilterOptions README and FilterColapsible minor bug

- CHANGELOG.md
- react/components/Radio/index.js
- react/components/RadioGroup/index.js
Add CSS classes to enable customization in Store Framework.
[Running workspace](https://brenovtex--otomask.myvtex.com/)
n/a
> Add CSS handles to Radio and RadioGroup

- CHANGELOG.md
- manifest.json
- package.json
- `isOverflowHidden` prop to the `Collapsible` component.
- CSS handles to RadioGroup and Radio.
- **FilterOptions** behaviour and example.
- **ColorPicker** hex validation.
- **InputSearch** component icon unaligned.
> Release v9.129.0

- CHANGELOG.md
- manifest.json
- package.json
- react/components/AutocompleteInput/index.tsx
On #1326, I forgot to add the new props to the root element 😢
> Fix AutocompleteInput exported types

- CHANGELOG.md
- manifest.json
- package.json
Fix Spinner Performance in #1333
> Release v9.130.2

- CHANGELOG.md
- manifest.json
- package.json
- `EXPERIMENTAL_Modal`.
- `useDisclosure` utils.
- **AutocompleteInput** term should follow `input.value` changes to allow input control outside the component.
> Release v9.131.0

- CHANGELOG.md
- manifest.json
- package.json
> Release v9.133.1

- CHANGELOG.md
- manifest.json
- package.json
- **EXPERIMENTAL_Modal** height on small screens.
- **EXPERIMENTAL_Modal** overflown content overlapping on iOS Safari.
- `utilities` folder not being compiled on the package build.
> Release v9.133.3

- CHANGELOG.md
- manifest.json
- package.json
- Class `vtex-tag` on `Tag` component.
> Release v9.134.0

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Textarea/index.js
Add CSS handles in textarea component
Zendesk ticket #325111
[Running workspace](https://iespinoza--arteni.myvtex.com/contact-us)
> add: css handle in textarea

- CHANGELOG.md
- manifest.json
- package.json
- **PageBlock** responsiveness issue on aside variation.
- **EXPERIMENTAL_TableV2** rows height when using `disableScroll`.
> Release v9.135.2

- CHANGELOG.md
- manifest.json
- package.json
- react/components/Slider/README.md
- react/components/Slider/index.js
Allows controlling the `Slider` value programmatically.
https://github.com/vtex-apps/store-discussion/issues/469
[Running workspace](https://sliderinputs--storecomponents.myvtex.com/apparel---accessories/eyeglasses/)
<details>
```tsx
import React, { useState } from 'react'
import Slider from '../Slider'
import Input from '../Input'
import Button from '../Button'
const Playground = () => {
const [inputValues, setInputValues] = useState({ left: '0', right: '99' })
const [values, setValues] = useState({ left: 0, right: 99 })
const { left, right } = values
const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => { …
```
> add values prop to the Slider

- CHANGELOG.md
- manifest.json
- package.json
- react/modules/scrollPollyfill.js
- **Modal** scroll dependency polyfill need.
> Release v9.136.1

- CHANGELOG.md
- manifest.json
- package.json
- Possibility to get callback on toggle fields visibility with `onToggleColumn`, `onHideAllColumns` and `onShowAllColumns`
> Release v9.144.0

- react/components/Dropdown/index.js
As the title says, this PR aims to remove unused methods/props on the Dropdown component.
#1417
> Removed unused methods on Dropdown

- CHANGELOG.md
related to #1427 .
- **NumericStepper** not working after switching from touch devices.
> Updates Changelog entry

- CHANGELOG.md
- manifest.json
- package.json
<details>
```jsx
<Layout fullWidth pageHeader={<PageHeader title="Playground" />}>
{/* Add your code here, don't forget to delete after */}
</Layout>
)
export default Playground
```
</details>
> Release v9.146.9

- CHANGELOG.md
- manifest.json
- package.json
> chore: release
